import type { CarV } from './car'
import type { JewelV } from './jewel'
import type { ObjV } from './objects'
import type { PaintV } from './painting'
import type { WatchV } from './watch'

/**
 * One illustration recipe per Black Market lot. Each lot is drawn from its own
 * parameters (case shape, bezel, dial, strap; stone, cut, setting; body,
 * livery; composition; object form) so no two lots share a picture.
 * qa: `visualSignature` must be unique across the market.
 */
export type Visual = WatchV | JewelV | PaintV | CarV | ObjV

const w = (v: Omit<WatchV, 'k'>): WatchV => ({ k: 'watch', ...v })
const j = (v: Omit<JewelV, 'k'>): JewelV => ({ k: 'jewel', ...v })
const p = (scene: PaintV['scene'], frame: PaintV['frame'], portrait = false): PaintV => ({ k: 'paint', scene, frame, portrait })
const c = (v: Omit<CarV, 'k'>): CarV => ({ k: 'car', ...v })
const o = (form: ObjV['form'], c1: string, extra: Omit<ObjV, 'k' | 'form' | 'c1'> = {}): ObjV => ({ k: 'obj', form, c1, ...extra })

export const VISUALS: Record<string, Visual> = {
  // ⌚ WATCHES
  watch_rolex_submariner: w({ case: 'round', metal: 'steel', dial: '#101114', bezel: 'diver', insert: ['#0c0c0e'], strap: 'oyster', numerals: 'dots', date: true }),
  watch_rolex_daytona: w({ case: 'round', metal: 'steel', dial: '#f4f2ec', bezel: 'tachy', insert: ['#111'], strap: 'oyster', sub: 3, subColor: '#111', hands: '#222' }),
  watch_rolex_gmt: w({ case: 'round', metal: 'steel', dial: '#111', bezel: 'gmt', insert: ['#1f3f9a', '#b3202a'], strap: 'jubilee', numerals: 'dots', date: true, accent: '#d0202a' }),
  watch_rolex_gmt2: w({ case: 'round', metal: 'steel', dial: '#111', bezel: 'gmt', insert: ['#b3202a', '#101010'], strap: 'oyster', numerals: 'dots', date: true, accent: '#2e9a4a' }),
  watch_rolex_datejust: w({ case: 'round', metal: 'steel', dial: '#c9ccd4', bezel: 'fluted', strap: 'jubilee', numerals: 'baton', date: true, hands: '#333' }),
  watch_rolex_daydate: w({ case: 'round', metal: 'gold', dial: '#e8d9a8', bezel: 'fluted', strap: 'president', numerals: 'baton', day: true, date: true, hands: '#5a4212' }),
  watch_rolex_explorer: w({ case: 'round', metal: 'steel', dial: '#0f0f10', strap: 'oyster', numerals: 'arabic' }),
  watch_rolex_explorer2: w({ case: 'round', metal: 'steel', dial: '#f5f3ee', bezel: 'h24', insert: ['#c9ccd4'], strap: 'oyster', numerals: 'dots', date: true, hands: '#111', accent: '#ff6a00' }),
  watch_rolex_milgauss: w({ case: 'round', metal: 'steel', dial: '#1a2230', strap: 'oyster', numerals: 'baton', extra: 'lightning', accent: '#ff7a1a', tone: 'green' }),
  watch_rolex_seadweller: w({ case: 'big', metal: 'steel', dial: '#0b0b0d', bezel: 'diver', insert: ['#050506'], strap: 'oyster', numerals: 'dots', date: true, accent: '#c92a2a', tone: 'navy' }),
  watch_patek_nautilus: w({ case: 'porthole', metal: 'steel', dial: '#26405e', strap: 'integrated', numerals: 'baton', extra: 'stripes', date: true, tone: 'navy' }),
  watch_patek_calatrava: w({ case: 'round', metal: 'gold', dial: '#f7f3ea', strap: 'leather', strapColor: '#101010', numerals: 'baton', hands: '#6a4a12' }),
  watch_ap_royal_oak: w({ case: 'octagon', metal: 'steel', dial: '#1d2c4a', bezel: 'screws', strap: 'integrated', numerals: 'baton', extra: 'tapisserie', date: true }),
  watch_ap_offshore: w({ case: 'octagon', metal: 'black', dial: '#141414', bezel: 'screws', strap: 'rubber', sub: 3, subColor: '#2a2a2a', numerals: 'arabic', accent: '#e8a02a' }),
  watch_rm_011: w({ case: 'tonneau', metal: 'ti', dial: '#1a1d22', bezel: 'screws', strap: 'rubber', strapColor: '#b3202a', numerals: 'none', extra: 'skeleton', accent: '#e02a2a' }),
  watch_rm_27: w({ case: 'tonneau', metal: 'black', dial: '#0e0e10', strap: 'rubber', strapColor: '#e8e2d2', numerals: 'none', extra: 'tourbillon', accent: '#c9e02a', tone: 'green' }),
  watch_vc_overseas: w({ case: 'round', metal: 'steel', dial: '#1b3a74', bezel: 'notched', strap: 'integrated', numerals: 'baton', date: true, tone: 'navy' }),
  watch_vc_patrimony: w({ case: 'round', metal: 'rose', dial: '#e9e4da', strap: 'leather', strapColor: '#5a3218', numerals: 'dots', hands: '#7e4834' }),
  watch_cartier_santos: w({ case: 'square', metal: 'gold', dial: '#f4f1ea', bezel: 'screws', strap: 'oyster', numerals: 'roman', hands: '#1f3f9a' }),
  watch_cartier_tank: w({ case: 'rect', metal: 'gold', dial: '#f6f3ec', strap: 'leather', strapColor: '#0f0f10', numerals: 'roman', hands: '#1f3f9a' }),
  watch_omega_speedmaster: w({ case: 'round', metal: 'steel', dial: '#0e0e10', bezel: 'tachy', insert: ['#111'], strap: 'oyster', sub: 3, subColor: '#1c1c1e', numerals: 'baton', tone: 'ink' }),
  watch_omega_seamaster: w({ case: 'round', metal: 'steel', dial: '#1b3a74', bezel: 'diver', insert: ['#16306a'], strap: 'oyster', numerals: 'dots', extra: 'waves', tone: 'navy' }),
  watch_jlc_reverso: w({ case: 'rect', metal: 'steel', dial: '#e9e6de', strap: 'leather', strapColor: '#2a1a10', numerals: 'arabic', extra: 'gadroon', hands: '#222' }),
  watch_lange_1: w({ case: 'round', metal: 'gold', dial: '#ece8de', strap: 'leather', strapColor: '#3a2412', numerals: 'roman', extra: 'bigdate', hands: '#6a4a12' }),
  watch_breguet_classique: w({ case: 'round', metal: 'gold', dial: '#e6e2d8', strap: 'leather', strapColor: '#101010', numerals: 'roman', extra: 'guilloche', hands: '#1f3f9a' }),
  watch_hublot_bigbang: w({ case: 'round', metal: 'ti', dial: '#101012', bezel: 'screws', strap: 'rubber', sub: 3, subColor: '#222', numerals: 'baton', accent: '#e02a2a' }),
  watch_tag_monaco: w({ case: 'square', metal: 'steel', dial: '#1f4fa0', strap: 'leather', strapColor: '#101010', sub: 2, subColor: '#f4f1ea', numerals: 'baton', accent: '#e02a2a', tone: 'navy' }),
  watch_iwc_portugieser: w({ case: 'big', metal: 'steel', dial: '#f7f6f2', strap: 'leather', strapColor: '#1a1a1a', sub: 2, subColor: '#eeeae0', numerals: 'arabic', hands: '#1f3f9a' }),
  watch_zenith_elprimero: w({ case: 'round', metal: 'steel', dial: '#f2f2ee', bezel: 'tachy', insert: ['#d9dde3'], strap: 'oyster', sub: 3, subColor: '#3a6ab0', numerals: 'baton', hands: '#222', accent: '#e02a2a' }),
  watch_panerai_luminor: w({ case: 'cushion', metal: 'steel', dial: '#0f0f10', strap: 'leather', strapColor: '#6a4020', numerals: 'big', extra: 'crownguard', hands: '#e8e2c8' }),
  watch_patek_grand: w({ case: 'pocket', metal: 'gold', dial: '#fbf8f0', strap: 'chain', sub: 3, subColor: '#f0ebe0', numerals: 'roman', extra: 'moon', hands: '#222', tone: 'plum' }),
  antique_breguet_pocket: w({ case: 'pocket', metal: 'gold', dial: '#e8e4da', strap: 'chain', numerals: 'roman', extra: 'guilloche', hands: '#1f3f9a' }),
  watch_casio_f91w: w({ case: 'digital', metal: 'black', dial: '#1a1a1c', strap: 'resin', numerals: 'none', tone: 'ink' }),
  watch_trench: w({ case: 'round', metal: 'silver', dial: '#f0e9d6', strap: 'leather', strapColor: '#6a4a2a', numerals: 'arabic', extra: 'grille', hands: '#2a2a2a' }),
  watch_railroad: w({ case: 'pocket', metal: 'silver', dial: '#fbfaf5', strap: 'chain', numerals: 'big', hands: '#111' }),
  watch_vostok: w({ case: 'round', metal: 'steel', dial: '#1f5a3a', bezel: 'diver', insert: ['#1a1a1a'], strap: 'nato', strapColor: '#3a4a2a,#3a4a2a', numerals: 'baton', extra: 'star', tone: 'green' }),
  watch_hamilton_ventura: w({ case: 'shield', metal: 'gold', dial: '#1a1a1a', strap: 'leather', strapColor: '#101010', numerals: 'baton', hands: '#e8d9a8' }),
  watch_longines_lindbergh: w({ case: 'big', metal: 'silver', dial: '#f5f1e6', bezel: 'hour', insert: ['#dcd8cc'], strap: 'leather', strapColor: '#4a2e18', numerals: 'arabic', hands: '#1f3f9a' }),
  watch_buhr: w({ case: 'big', metal: 'steel', dial: '#0c0c0d', strap: 'leather', strapColor: '#2a1a12', numerals: 'arabic', extra: 'triangle', hands: '#e8e2c8' }),
  watch_seiko_astron: w({ case: 'cushion', metal: 'gold', dial: '#d9c490', strap: 'mesh', numerals: 'baton', extra: 'texture', hands: '#5a4212' }),

  // 💎 JEWELRY
  jewel_cartier_love: j({ form: 'bangle', metal: 'gold', gem: 'none' }),
  jewel_cartier_panthere: j({ form: 'panther', metal: 'gold', gem: '#2ecc71', gem2: '#141414' }),
  jewel_tiffany_diamond: j({ form: 'gem', metal: 'plat', gem: '#f7d358', cut: 'cushion', tone: 'navy' }),
  jewel_tiffany_setting: j({ form: 'solitaire', metal: 'plat', gem: '#f4f8fc', tone: 'navy' }),
  jewel_bulgari_serpenti: j({ form: 'serpent', metal: 'gold', gem: '#2ecc71' }),
  jewel_vca_alhambra: j({ form: 'clover', metal: 'gold', gem: '#1e8a5a', gem2: '#f2eee4', tone: 'green' }),
  jewel_winston: j({ form: 'riviere', metal: 'plat', gem: '#f4f8fc', gem2: '#e8eef6', tone: 'ink' }),
  jewel_graff: j({ form: 'cocktail', metal: 'plat', gem: '#f9e0ec', gem2: '#f4f8fc', cut: 'emerald', tone: 'plum' }),
  jewel_artdeco_brooch: j({ form: 'deco', metal: 'plat', gem: '#f4f8fc', gem2: '#f4f8fc', tone: 'ink' }),
  jewel_victorian_emerald: j({ form: 'ring', metal: 'gold', gem: '#1e9a5a', cut: 'emerald', tone: 'green' }),
  jewel_sapphire_ring: j({ form: 'cocktail', metal: 'plat', gem: '#1f4fb0', gem2: '#f4f8fc', cut: 'oval', tone: 'navy' }),
  jewel_ruby_necklace: j({ form: 'riviere', metal: 'plat', gem: '#b3122a', gem2: '#f4f8fc', cut: 'oval' }),
  jewel_pearl_necklace: j({ form: 'pearls', metal: 'gold', gem: '#f3eee4' }),
  jewel_emerald_cocktail: j({ form: 'cocktail', metal: 'gold', gem: '#1a9a52', gem2: '#f4f8fc', cut: 'emerald', tone: 'green' }),
  jewel_diamond_tiara: j({ form: 'tiara', metal: 'plat', gem: '#f4f8fc', gem2: '#e8eef6', tone: 'navy' }),
  jewel_vca_high: j({ form: 'flower', metal: 'gold', gem: '#b3122a', gem2: '#f4f8fc' }),
  jewel_cartier_high: j({ form: 'tiara', metal: 'gold', gem: '#1a9a52', gem2: '#f4f8fc', cut: 'emerald', tone: 'green' }),
  jewel_artdeco_rare: j({ form: 'deco', metal: 'plat', gem: '#1f4fb0', gem2: '#f4f8fc', cut: 'cushion', tone: 'navy' }),
  jewel_silver_ring: j({ form: 'ring', metal: 'silver', gem: '#141418', cut: 'emerald', tone: 'ink' }),
  jewel_cameo_brooch: j({ form: 'cameo', metal: 'gold', gem: '#c9744a', gem2: '#f2e6d6' }),
  jewel_garnet_necklace: j({ form: 'riviere', metal: 'gold', gem: '#7a1020', gem2: '#8a1a2a', cut: 'rose' }),
  jewel_amber_brooch: j({ form: 'brooch', metal: 'silver', gem: '#e8932a', gem2: '#c96a1a', cut: 'cabochon', tone: 'warm' }),
  jewel_girandole: j({ form: 'girandole', metal: 'silver', gem: '#f4f8fc', gem2: '#f4f8fc' }),
  jewel_charm_bracelet: j({ form: 'charm', metal: 'gold', gem: '#c0392b', gem2: '#2e86c1', tone: 'warm' }),
  jewel_rose_cut: j({ form: 'gem', metal: 'silver', gem: '#e9edf2', cut: 'rose', tone: 'ink' }),
  jewel_opal_ring: j({ form: 'ring', metal: 'gold', gem: '#5ab0c8', cut: 'cabochon', tone: 'navy' }),
  jewel_nouveau_pendant: j({ form: 'pendant', metal: 'gold', gem: '#5aa87a', gem2: '#9ad0c0', tone: 'green' }),

  // 🖼️ ART
  art_vangogh_starry: p('starry', 'ornate'),
  art_vinci_mona: p('mona', 'ornate', true),
  art_vinci_supper: p('supper', 'fresco'),
  art_munch_scream: p('scream', 'wood', true),
  art_monet_impression: p('impression', 'gold'),
  art_monet_lilies: p('lilies', 'gold'),
  art_dali_memory: p('dali', 'black'),
  art_picasso_guernica: p('guernica', 'black'),
  art_picasso_avignon: p('avignon', 'wood', true),
  art_vermeer_pearl: p('pearl', 'gold', true),
  art_botticelli_venus: p('venus', 'ornate'),
  art_michelangelo_adam: p('adam', 'fresco'),
  art_caravaggio_matthew: p('caravaggio', 'ornate'),
  art_rembrandt_watch: p('nightwatch', 'ornate'),
  art_klimt_kiss: p('kiss', 'gold', true),
  art_warhol_marilyn: p('pop', 'black', true),
  art_malevich_square: p('square', 'wood', true),
  art_kandinsky_viii: p('kandinsky', 'black'),
  art_seurat_grande_jatte: p('seurat', 'gold'),
  art_litho_belle: p('poster', 'mat', true),
  art_engraving_port: p('engraving', 'mat'),
  art_watercolor_paris: p('watercolor', 'mat', true),
  art_salon_landscape: p('landscape', 'ornate'),
  art_still_life_study: p('stilllife', 'wood'),
  art_portrait_school: p('portrait', 'ornate', true),
  art_hokusai_wave: p('wave', 'mat'),
  art_vangogh_sunflowers: p('sunflowers', 'gold', true),
  art_turner_temeraire: p('temeraire', 'gold'),
  art_bruegel_hunters: p('hunters', 'wood'),

  // 🚗 CARS
  car_ferrari_250_gto: c({ body: 'gt60', color: '#c8161d', stripe: '#f4f1ea', number: '3', wheels: 'wire' }),
  car_ferrari_f40: c({ body: 'f40', color: '#d0141c', wing: true }),
  car_ferrari_enzo: c({ body: 'hyper', color: '#b8121a', accent: '#111' }),
  car_ferrari_laferrari: c({ body: 'hyper', color: '#e21d24' }),
  car_lambo_miura: c({ body: 'miura', color: '#f28a1a' }),
  car_lambo_countach: c({ body: 'wedge', color: '#f4f1ea', wing: true }),
  car_lambo_diablo: c({ body: 'wedge', color: '#6a2aa8' }),
  car_lambo_aventador: c({ body: 'hyper', color: '#8ac62a', accent: '#111' }),
  car_porsche_911: c({ body: 'p911', color: '#c9ccd2' }),
  car_porsche_959: c({ body: 'p911', color: '#f4f1ea', accent: '#b9bdc4' }),
  car_porsche_carrera_gt: c({ body: 'hyper', color: '#9aa3ad' }),
  car_porsche_918: c({ body: 'hyper', color: '#e9eef2', stripe: '#1f5fb0' }),
  car_mb_300sl: c({ body: 'gull', color: '#c9ccd4' }),
  car_mb_300slr: c({ body: 'racer', color: '#d9dde3', number: '722' }),
  car_mb_540k: c({ body: 'prewar', color: '#1a1a1a', accent: '#8a1a1a' }),
  car_mb_slr: c({ body: 'etype', color: '#6f7780' }),
  car_am_db5: c({ body: 'gt60', color: '#b8b8b0', wheels: 'wire' }),
  car_am_db9: c({ body: 'gtcoupe', color: '#1f3a2a' }),
  car_am_valkyrie: c({ body: 'hyper', color: '#1e6a4a', stripe: '#c8e02a' }),
  car_jaguar_etype: c({ body: 'etype', color: '#1f4a32', wheels: 'wire' }),
  car_jaguar_xj220: c({ body: 'hyper', color: '#3a5a8a' }),
  car_mclaren_f1: c({ body: 'hyper', color: '#e87a1a', accent: '#2a2a2a' }),
  car_mclaren_p1: c({ body: 'hyper', color: '#f2e22a', wing: true }),
  car_bugatti_veyron: c({ body: 'atlantic', color: '#1f2f5a', accent: '#9aa3ad', wheels: 'alloy' }),
  car_bugatti_chiron: c({ body: 'hyper', color: '#16306a', accent: '#0c0c10', stripe: '#9aa3ad' }),
  car_bugatti_atlantic: c({ body: 'atlantic', color: '#1b2430' }),
  car_rr_phantom: c({ body: 'sedan', color: '#141418', accent: '#6a1a2a' }),
  car_rr_silver_ghost: c({ body: 'veteran', color: '#d0d2d4', accent: '#6a6a6a' }),
  car_bentley_continental: c({ body: 'gtcoupe', color: '#2a3a2e', accent: '#1a1a1a' }),
  car_ford_gt40: c({ body: 'racer', color: '#8ec8e8', stripe: '#f28a1a', number: '6' }),
  car_shelby_cobra: c({ body: 'roadster', color: '#1f4fb0', stripe: '#f4f1ea', wheels: 'wire' }),
  car_toyota_2000gt: c({ body: 'etype', color: '#f4f1ea' }),
  car_nissan_r34: c({ body: 'boxy', color: '#1f5fc0', wing: true }),
  car_bmw_507: c({ body: 'roadster', color: '#f4f1ea', accent: '#b3202a' }),
  car_bmw_m1: c({ body: 'wedge', color: '#f4f1ea', stripe: '#1f5fb0', number: '1' }),
  car_audi_quattro: c({ body: 'boxy', color: '#f4f1ea', stripe: '#b3202a', number: '1' }),
  car_delorean: c({ body: 'wedge', color: '#b9bec4', accent: '#2a2a2a' }),
  car_citroen_ds: c({ body: 'ds', color: '#141414', accent: '#c9ccd2' }),
  car_lancia_stratos: c({ body: 'wedge', color: '#1f6fb0', stripe: '#2e9a4a', number: '4', wing: true }),
  car_alfa_33_stradale: c({ body: 'racer', color: '#b3121a' }),
  car_vw_beetle: c({ body: 'beetle', color: '#6fa8d8', wheels: 'steel' }),
  car_fiat_500: c({ body: 'fiat500', color: '#f2e2b8', wheels: 'steel' }),
  car_mini: c({ body: 'mini', color: '#b3202a', accent: '#f4f1ea', wheels: 'steel' }),
  car_citroen_2cv: c({ body: 'cv2', color: '#b8c9b0', wheels: 'steel' }),
  car_ford_t: c({ body: 'veteran', color: '#141414', accent: '#141414' }),

  // 🏺 ANTIQUES
  antique_bronze_candlestick: o('candlestick', '#8f6532', { metal: 'bronze' }),
  antique_victorian_box: o('casket', '#5a2a1a', { metal: 'brass', c2: '#c9a45a' }),
  antique_artdeco_clock: o('mantelclock', '#1a1a1e', { metal: 'steel', c2: '#6a6a70' }),
  antique_porcelain_vase: o('vase', '#f4f1ea', { c2: '#d4af58', metal: 'gold' }),
  antique_ming_vase: o('vase', '#f2f4f8', { c2: '#1f3f9a', tone: 'navy' }),
  antique_japan_ceramic: o('bowl', '#3a2a24', { c2: '#8a6a4a', tone: 'ink' }),
  antique_samurai_box: o('casket', '#141010', { metal: 'gold', c2: '#d4af58', tone: 'velvet' }),
  antique_silver_snuff: o('snuffbox', '#6a8ab0', { metal: 'silver' }),
  antique_silver_service: o('teaset', '#fff', { metal: 'silver', tone: 'ink' }),
  antique_globe: o('globe', '#c9b27a', { metal: 'brass', c2: '#7a5a2a' }),
  antique_telescope: o('telescope', '#fff', { metal: 'brass', c2: '#5a3a1a', tone: 'navy' }),
  antique_typewriter: o('typewriter', '#141414', { metal: 'steel' }),
  antique_artdeco_lamp: o('lamp', '#e8c07a', { metal: 'bronze', tone: 'plum' }),
  antique_music_box: o('musicbox', '#5a3218', { metal: 'brass' }),
  antique_automaton: o('automaton', '#2e8a5a', { metal: 'gold', c2: '#6a4a2a', tone: 'green' }),
  antique_leica_camera: o('rangefinder', '#1a1a1a', { metal: 'steel', tone: 'ink' }),
  antique_compass: o('compass', '#fff', { metal: 'brass', c2: '#1a1a1a' }),
  antique_bronze_figure: o('figure', '#fff', { metal: 'bronze', tone: 'green' }),
  antique_world_map: o('map', '#6a8a5a'),
  antique_staunton_chess: o('chess', '#fff', { tone: 'wall' }),
  antique_tula_samovar: o('samovar', '#b3202a', { metal: 'copper' }),
  antique_cobalt_net: o('cup', '#1f3f8a', { tone: 'navy' }),
  book_gatsby: o('book', '#16244a', { c2: '#f2c94a', mark: 'eyes', metal: 'gold', tone: 'navy' }),
  book_hobbit: o('book', '#3a6a5a', { c2: '#e8e2c8', mark: 'mountain', tone: 'green' }),
  book_potter: o('book', '#8a1a1a', { c2: '#f2c94a', mark: 'bolt', tone: 'velvet' }),
  book_first_folio: o('openbook', '#5a3218', { c2: '#b3202a', mark: 'portrait' }),
  book_gutenberg: o('openbook', '#3a1a10', { c2: '#1f3f9a', tone: 'plum' }),
  book_atlas: o('book', '#6a4a2a', { c2: '#d4af58', mark: 'globe' }),
  book_victorian_illust: o('book', '#1f4a3a', { c2: '#d4af58', mark: 'ornate', tone: 'green' }),
  book_verne: o('book', '#a01a1a', { c2: '#d4af58', mark: 'gear' }),
  book_doyle: o('book', '#d8c9a0', { c2: '#3a2a1a', mark: 'pipe', tone: 'ink' }),
  book_russian_classic: o('book', '#3a1418', { c2: '#c9a45a', mark: 'bands', tone: 'velvet' }),
  sci_astro_globe: o('celestial', '#16244a', { metal: 'brass', tone: 'navy' }),
  sci_microscope: o('microscope', '#fff', { metal: 'brass', tone: 'ink' }),
  sci_chronometer: o('chronometer', '#5a2a14', { metal: 'brass' }),
  sci_nav_compass: o('binnacle', '#4a3018', { metal: 'brass', c2: '#1a1a1a', tone: 'navy' }),
  sci_diving_helmet: o('helmet', '#fff', { metal: 'copper', tone: 'navy' }),
  sci_medical_set: o('medkit', '#3a1a14', { c2: '#6a1a2a', tone: 'velvet' }),
  sci_lab_kit: o('flasks', '#9ad0e8', { metal: 'brass', c2: '#e8a02a', tone: 'ink' }),
  sci_survey: o('theodolite', '#fff', { metal: 'brass', tone: 'green' }),
  sci_sextant: o('sextant', '#fff', { metal: 'brass', tone: 'navy' }),
  sci_astro_rare: o('armillary', '#e8a02a', { metal: 'gold', tone: 'plum' }),

  // 👑 COLLECTIBLES
  fashion_birkin: o('birkin', '#c56d2b', { metal: 'gold' }),
  fashion_kelly: o('kelly', '#141414', { metal: 'gold', tone: 'velvet' }),
  fashion_chanel_255: o('flap', '#16161a', { metal: 'gold', tone: 'ink' }),
  fashion_lv_trunk: o('trunk', '#6a4222', { c2: '#e0b870', metal: 'brass' }),
  fashion_lv_steamer: o('steamer', '#5a3a1e', { c2: '#e0b870', metal: 'brass', tone: 'ink' }),
  fashion_gucci_bamboo: o('bamboo', '#1a1a1a', { metal: 'gold', tone: 'green' }),
  fashion_lady_dior: o('ladydior', '#e8c8d0', { metal: 'gold', tone: 'plum' }),
  fashion_fendi_baguette: o('baguette', '#8a5a2a', { metal: 'gold' }),
  fashion_hermes_scarf: o('scarf', '#e8742a', { c2: '#f6e7c8', tone: 'velvet' }),
  fashion_chanel_tweed: o('jacket', '#f0e8da', { c2: '#16161a', metal: 'gold', tone: 'ink' }),
  fashion_rolex_case: o('watchbox', '#1e5a3a', { c2: '#e8e2d2', metal: 'gold', tone: 'green' }),
  tech_leica_m3: o('rangefinder', '#161616', { metal: 'silver', mark: 'red' }),
  tech_leica_m6: o('rangefinder', '#0c0c0e', { metal: 'black', mark: 'red', tone: 'studio' }),
  tech_hasselblad_500c: o('boxcamera', '#141414', { metal: 'silver', tone: 'studio' }),
  tech_polaroid_sx70: o('polaroid', '#2a2a2e', { metal: 'silver', tone: 'studio' }),
  tech_mac_128k: o('mac', '#e8e2d0', { tone: 'studio' }),
  tech_walkman: o('walkman', '#3a5aa8', { c2: '#c9ccd2', tone: 'navy' }),
  tech_gameboy: o('gameboy', '#c9c6be', { tone: 'studio' }),
  tech_atari_2600: o('console', '#6a4222', { tone: 'warm' }),
  tech_ibm_model_m: o('keyboard', '#d9d4c6', { c2: '#efebe0', tone: 'studio' }),
  tech_braun_sk4: o('radiogram', '#f2f0ea', { tone: 'studio' }),
  tech_beogram: o('turntable', '#c9ccd2', { c2: '#1a1a1a', mark: 'dots', tone: 'studio' }),
  tech_marshall_amp: o('amp', '#1a1a1a', { c2: '#d4af58', metal: 'gold', mark: 'Marshall', tone: 'ink' }),
  tech_technics_1200: o('turntable', '#2a2a2e', { c2: '#b9bec4', tone: 'ink' }),
  music_strat_50s: o('guitar', '#e8b86a', { c2: '#e8dcc0', tone: 'navy' }),
  music_lespaul_59: o('lespaul', '#c96a1a', { tone: 'warm' }),
  music_flying_v: o('flyingv', '#f0e6d0', { tone: 'ink' }),
  music_p_bass: o('bass', '#b3202a', { c2: '#e8dcc0', tone: 'studio' }),
  music_steinway: o('piano', '#0c0c0e', { tone: 'wall' }),
  music_stradivari: o('violin', '#a8501a', { tone: 'plum' }),
  music_vintage_mic: o('mic', '#1a1a1a', { metal: 'silver', tone: 'ink' }),
  music_tube_amp: o('amp', '#6a4a2a', { c2: '#b3202a', metal: 'steel', mark: 'Vox', tone: 'velvet' }),
  music_turntable: o('turntable', '#5a3a1e', { c2: '#d4af58', tone: 'warm' }),
  music_rare_vinyl: o('vinyl', '#e8a02a', { c2: '#1f3f8a', tone: 'plum' }),
  coin_denarius: o('coin', '#fff', { metal: 'silver', mark: 'head', tone: 'ink' }),
  coin_owl: o('coin', '#fff', { metal: 'silver', mark: 'owl', tone: 'navy' }),
  coin_morgan: o('coin', '#fff', { metal: 'steel', mark: 'liberty', tone: 'green' }),
  toy_steiff_bear: o('bear', '#c99a5a', { c2: '#e8d2a8', metal: 'silver', tone: 'warm' }),
  toy_rubik: o('cube', '#fff', { tone: 'studio' }),
  sport_t206: o('card', '#7a8a6a', { c2: '#3a4a6a', mark: 'WAGNER', tone: 'wall' }),

  // 💰 RARE OBJECTS (DuckJackpot lore) & specials
  special_faberge_egg: o('egg', '#b3202a', { metal: 'gold', c2: '#f4f8fc', tone: 'plum' }),
  special_mystery: o('mystery', '#141418', { metal: 'gold', c2: '#d4af58', tone: 'ink' }),
  rare_first_duckcoin: o('duckcoin', '#fff', { metal: 'gold', mark: 'No 1' }),
  rare_vault_key: o('key', '#1f4fb0', { metal: 'brass', mark: 'B-07' }),
  rare_mansion_seal: o('seal', '#9a1a1a', { metal: 'gold', c2: '#2a1a12', tone: 'velvet' }),
  rare_gold_bar: o('goldbar', '#fff', { metal: 'gold', mark: 'DUCK RESERVE' }),
  rare_laser_prism: o('prism', '#9ad8ff', { tone: 'ink' }),
  rare_black_ledger: o('ledger', '#d4af58', { metal: 'gold', tone: 'velvet' }),
  rare_skyline_crown: o('crown', '#1f4fb0', { metal: 'gold', c2: '#b3122a', tone: 'navy' }),
  rare_grand_vault_key: o('key', '#b3122a', { metal: 'gold', mark: 'GRAND', tone: 'plum' }),
  rare_duck_statue: o('duck', '#fff', { metal: 'gold', tone: 'plum' }),
  rare_cctv_tape: o('tape', '#f2e6c8', { mark: 'BANK CAM 01', tone: 'ink' }),
}

export function visualSignature(v: Visual) {
  return JSON.stringify(v)
}
