import type { LotDraft } from '../catalog'
import { C } from './helpers'

export const ART_LOTS: LotDraft[] = [
  C(
    'art_sketch',
    'Ренуар — «Бал в Мулен де ла Галетт»',
    'Renoir — Bal du moulin de la Galette',
    'Пьер-Огюст Ренуар',
    'Pierre-Auguste Renoir',
    '1876',
    '1876',
    'Тёплый вечер на Монмартре: свет фонарей, движение толпы и воздух Парижа.',
    'A warm Montmartre evening: lantern light, a moving crowd, and Paris in the air.',
    'Одна из самых известных сцен парижской жизни XIX века.',
    'One of the most famous scenes of nineteenth-century Paris life.',
    'Фиксирует рождение современного городского праздника и импрессионистского взгляда на свет.',
    'It captures the modern city fête and the Impressionist eye for light.',
    'LUX',
    'ART',
    40,
    48,
    { image: '/heist/lots/art_sketch.webp' },
  ),
  C(
    'art_vangogh_starry',
    'Винсент ван Гог — «Звёздная ночь»',
    'Vincent van Gogh — The Starry Night',
    'Винсент ван Гог',
    'Vincent van Gogh',
    '1889',
    '1889',
    'Вихрь неба над тихим городком: кисть почти слышна.',
    'A whirling sky over a quiet town: you can almost hear the brush.',
    'Написана во время пребывания ван Гога в Сен-Реми.',
    'Painted during van Gogh’s stay in Saint-Rémy.',
    'Стала символом того, как личное видение меняет историю живописи.',
    'It became a symbol of how a private vision can change the history of painting.',
    'ICONIC',
    'ART',
    420000,
    485000,
    { limited: 8 },
  ),
  C(
    'art_vinci_mona',
    'Леонардо да Винчи — «Мона Лиза»',
    'Leonardo da Vinci — Mona Lisa',
    'Леонардо да Винчи',
    'Leonardo da Vinci',
    'ок. 1503–1519',
    'c. 1503–1519',
    'Портрет, который держит взгляд столетиями.',
    'A portrait that has held the gaze for centuries.',
    'Хранится в Лувре и считается одной из самых известных картин мира.',
    'Held in the Louvre and counted among the most famous paintings on earth.',
    'Эталон ренессансного портрета и культурный миф Запада.',
    'The benchmark of the Renaissance portrait and a Western cultural myth.',
    'ICONIC',
    'ART',
    8_000_000,
    9_200_000,
    { limited: 1 },
  ),
  C(
    'art_vinci_supper',
    'Леонардо да Винчи — «Тайная вечеря»',
    'Leonardo da Vinci — The Last Supper',
    'Леонардо да Винчи',
    'Leonardo da Vinci',
    'ок. 1495–1498',
    'c. 1495–1498',
    'Драма жеста и тишины за одним длинным столом.',
    'A drama of gesture and silence along one long table.',
    'Монументальная роспись в монастыре Санта-Мария-делле-Грацие.',
    'A monumental mural in the Santa Maria delle Grazie monastery.',
    'Ключевой образ христианского искусства и композиции Высокого Возрождения.',
    'A key image of Christian art and High Renaissance composition.',
    'ICONIC',
    'ART',
    3_500_000,
    4_050_000,
    { limited: 3 },
  ),
  C(
    'art_munch_scream',
    'Эдвард Мунк — «Крик»',
    'Edvard Munch — The Scream',
    'Эдвард Мунк',
    'Edvard Munch',
    '1893',
    '1893',
    'Фигура на мосту, небо как рана, звук которого все узнают.',
    'A figure on a bridge, a sky like a wound, a sound everyone knows.',
    'Существует несколько версий произведения.',
    'Several versions of the work exist.',
    'Икон тревоги XX века и мост от символизма к экспрессионизму.',
    'An icon of twentieth-century anxiety and a bridge from Symbolism to Expressionism.',
    'LEGENDARY',
    'ART',
    88000,
    99000,
  ),
  C(
    'art_monet_impression',
    'Клод Моне — «Впечатление. Восход солнца»',
    'Claude Monet — Impression, Sunrise',
    'Клод Моне',
    'Claude Monet',
    '1872',
    '1872',
    'Гавань в дымке, солнце как точка пульса.',
    'A harbour in haze, the sun a pulse of paint.',
    'Именно от названия этой картины произошло название движения «импрессионизм».',
    'The Impressionist movement takes its name from this painting.',
    'Манифест нового взгляда: свет важнее контура.',
    'A manifesto of a new eye: light over outline.',
    'LEGENDARY',
    'ART',
    72000,
    82000,
  ),
  C(
    'art_monet_lilies',
    'Клод Моне — «Водяные лилии»',
    'Claude Monet — Water Lilies',
    'Клод Моне',
    'Claude Monet',
    'серия, нач. XX в.',
    'series, early 20th c.',
    'Пруд Живерни как бесконечная тема цвета.',
    'The Giverny pond as an endless theme of colour.',
    'Моне создал множество вариантов одной темы.',
    'Monet made many versions of the same subject.',
    'Серия изменила масштаб декоративной живописи и путь к абстракции.',
    'The series changed the scale of decorative painting and the road to abstraction.',
    'EPIC',
    'ART',
    8600,
    9800,
  ),
  C(
    'art_dali_memory',
    'Сальвадор Дали — «Постоянство памяти»',
    'Salvador Dalí — The Persistence of Memory',
    'Сальвадор Дали',
    'Salvador Dalí',
    '1931',
    '1931',
    'Мягкие часы на жёстком каталонском берегу.',
    'Soft watches on a hard Catalan shore.',
    'Знаменитые «плавящиеся часы» стали символом сюрреализма.',
    'The melting watches became a symbol of Surrealism.',
    'Образ времени, который вошёл в массовую культуру XX века.',
    'An image of time that entered twentieth-century mass culture.',
    'LEGENDARY',
    'ART',
    64000,
    73000,
  ),
  C(
    'art_picasso_guernica',
    'Пабло Пикассо — «Герника»',
    'Pablo Picasso — Guernica',
    'Пабло Пикассо',
    'Pablo Picasso',
    '1937',
    '1937',
    'Чёрно-белая рана войны, растянутая на огромный холст.',
    'A black-and-white wound of war stretched across a vast canvas.',
    'Создана как реакция на разрушение баскского города Герника.',
    'Created in response to the destruction of the Basque town of Guernica.',
    'Один из главных антивоенных образов искусства XX века.',
    'One of the central anti-war images of twentieth-century art.',
    'ICONIC',
    'ART',
    1_200_000,
    1_380_000,
    { limited: 5 },
  ),
  C(
    'art_picasso_avignon',
    'Пабло Пикассо — «Авиньонские девицы»',
    'Pablo Picasso — Les Demoiselles d’Avignon',
    'Пабло Пикассо',
    'Pablo Picasso',
    '1907',
    '1907',
    'Пять фигур, которые ломают перспективу и лицо сразу.',
    'Five figures that break perspective and the face at once.',
    'Одно из произведений, связанных с зарождением кубизма.',
    'One of the works tied to the birth of Cubism.',
    'Точка, после которой европейская живопись уже не могла быть прежней.',
    'The point after which European painting could not stay the same.',
    'LEGENDARY',
    'ART',
    91000,
    104000,
  ),
  C(
    'art_vermeer_pearl',
    'Ян Вермеер — «Девушка с жемчужной серёжкой»',
    'Johannes Vermeer — Girl with a Pearl Earring',
    'Ян Вермеер',
    'Johannes Vermeer',
    'ок. 1665',
    'c. 1665',
    'Поворот головы, влажный блеск жемчуга, тишина Делфта.',
    'A turned head, the wet gleam of a pearl, the quiet of Delft.',
    'Часто называют «Мона Лизой Севера».',
    'Often called the Mona Lisa of the North.',
    'Вершина голландского камерного портрета и света на ткани.',
    'A summit of Dutch intimate portraiture and light on cloth.',
    'LEGENDARY',
    'ART',
    77000,
    88000,
  ),
  C(
    'art_botticelli_venus',
    'Сандро Боттичелли — «Рождение Венеры»',
    'Sandro Botticelli — The Birth of Venus',
    'Сандро Боттичелли',
    'Sandro Botticelli',
    '1480-е',
    '1480s',
    'Богиня на раковине выходит к берегу Флоренции.',
    'The goddess on a shell steps toward the Florentine shore.',
    'Один из символов итальянского Возрождения.',
    'One of the emblems of the Italian Renaissance.',
    'Античный миф, возвращённый в христианскую Италию как идеал красоты.',
    'A classical myth returned to Christian Italy as an ideal of beauty.',
    'LEGENDARY',
    'ART',
    69000,
    79000,
  ),
  C(
    'art_michelangelo_adam',
    'Микеланджело — «Сотворение Адама»',
    'Michelangelo — The Creation of Adam',
    'Микеланджело',
    'Michelangelo',
    '1508–1512',
    '1508–1512',
    'Два пальца почти касаются — и мир ещё не начался.',
    'Two fingers almost touch — and the world has not yet begun.',
    'Часть росписи потолка Сикстинской капеллы.',
    'Part of the Sistine Chapel ceiling.',
    'Самый цитируемый жест в истории европейского искусства.',
    'The most quoted gesture in the history of European art.',
    'ICONIC',
    'ART',
    2_200_000,
    2_530_000,
    { limited: 4 },
  ),
  C(
    'art_caravaggio_matthew',
    'Караваджо — «Призвание святого Матфея»',
    'Caravaggio — The Calling of Saint Matthew',
    'Караваджо',
    'Caravaggio',
    '1599–1600',
    '1599–1600',
    'Луч света режет тёмную таверну, как нож.',
    'A blade of light cuts a dark tavern.',
    'Знаменитая работа мастера светотени.',
    'A famous work by the master of chiaroscuro.',
    'Образец барокко: святое входит в грязный повседневный стол.',
    'A Baroque model: the sacred enters a dirty everyday table.',
    'EPIC',
    'ART',
    9400,
    10800,
  ),
  C(
    'art_rembrandt_watch',
    'Рембрандт — «Ночной дозор»',
    'Rembrandt — The Night Watch',
    'Рембрандт',
    'Rembrandt',
    '1642',
    '1642',
    'Ополчение Амстердама в движении, а не в позе.',
    'Amsterdam’s militia in motion, not in a pose.',
    'Одно из самых известных произведений голландского Золотого века.',
    'One of the most famous works of the Dutch Golden Age.',
    'Перевернул групповой портрет: свет, жест, городская гордость.',
    'It overturned the group portrait: light, gesture, civic pride.',
    'LEGENDARY',
    'ART',
    84000,
    96000,
  ),
  C(
    'art_klimt_kiss',
    'Густав Климт — «Поцелуй»',
    'Gustav Klimt — The Kiss',
    'Густав Климт',
    'Gustav Klimt',
    '1907–1908',
    '1907–1908',
    'Золотой плащ, двое на краю цветочного обрыва.',
    'A golden cloak, two figures on the edge of a flowered drop.',
    'Одно из главных произведений венского модерна.',
    'One of the central works of Viennese Modernism.',
    'Соединяет эмаль, эрос и декоративность fin de siècle.',
    'It joins enamel, eros and fin-de-siècle decoration.',
    'LEGENDARY',
    'ART',
    76000,
    87000,
  ),
  C(
    'art_warhol_marilyn',
    'Энди Уорхол — «Marilyn Diptych»',
    'Andy Warhol — Marilyn Diptych',
    'Энди Уорхол',
    'Andy Warhol',
    '1962',
    '1962',
    'Лицо звезды, повторённое до иконы и до призрака.',
    'A star’s face repeated into icon and ghost.',
    'Один из символов поп-арта.',
    'One of the emblems of Pop Art.',
    'Показывает, как слава и смерть работают как печатный станок.',
    'It shows how fame and death work like a printing press.',
    'LEGENDARY',
    'ART',
    58000,
    66000,
  ),
  C(
    'art_malevich_square',
    'Казимир Малевич — «Чёрный квадрат»',
    'Kazimir Malevich — Black Square',
    'Казимир Малевич',
    'Kazimir Malevich',
    '1915',
    '1915',
    'Чёрная плоскость как абсолютный жест.',
    'A black plane as an absolute gesture.',
    'Одно из наиболее известных произведений русского авангарда.',
    'One of the best-known works of the Russian avant-garde.',
    'Обнуляет сюжет и объявляет живопись чистой идеей.',
    'It zeros the subject and declares painting a pure idea.',
    'EPIC',
    'ART',
    7200,
    8300,
  ),
  C(
    'art_kandinsky_viii',
    'Василий Кандинский — «Композиция VIII»',
    'Wassily Kandinsky — Composition VIII',
    'Василий Кандинский',
    'Wassily Kandinsky',
    '1923',
    '1923',
    'Круги, линии и ритм как музыка без нот.',
    'Circles, lines and rhythm as music without notes.',
    'Важнейшая работа абстрактного искусства.',
    'A major work of abstract art.',
    'Показывает, что картина может строиться как партитура.',
    'It shows that a painting can be built like a score.',
    'EPIC',
    'ART',
    6800,
    7800,
  ),
  C(
    'art_seurat_grande_jatte',
    'Жорж Сёра — «Воскресный день на острове Гранд-Жатт»',
    'Georges Seurat — A Sunday on La Grande Jatte',
    'Жорж Сёра',
    'Georges Seurat',
    '1884–1886',
    '1884–1886',
    'Парижский выходной, собранный из цветных точек.',
    'A Paris Sunday assembled from coloured dots.',
    'Знаменитая работа, созданная методом пуантилизма.',
    'A famous work made with the pointillist method.',
    'Наука цвета стала большим городским спектаклем.',
    'The science of colour became a grand urban spectacle.',
    'EPIC',
    'ART',
    6100,
    7000,
  ),
]
