import type { LotDraft } from '../catalog'

/**
 * Black Market 2.1 — lots that fill the gaps in the collection: entry-level
 * watches and cars, earrings/bracelets/loose stones, coins, toys and a few
 * public-domain artworks. Facts are documented history (no auction records);
 * DuckJackpot lore lots are flagged `fictional`. Priced directly in DUCK COIN
 * so existing lot prices stay exactly as they were.
 */
type Text = [name: string, year: string, blurb: string, fact: string, why: string, history: string]

function X(
  id: string,
  category: LotDraft['category'],
  rarity: LotDraft['rarity'],
  price: number,
  maker: [string, string],
  ru: Text,
  en: Text,
  fictional = false,
): LotDraft {
  return {
    id,
    name: { ru: ru[0], en: en[0] },
    maker: { ru: maker[0], en: maker[1] },
    artist: { ru: maker[0], en: maker[1] },
    year: { ru: ru[1], en: en[1] },
    blurb: { ru: ru[2], en: en[2] },
    fact: { ru: ru[3], en: en[3] },
    significance: { ru: ru[4], en: en[4] },
    history: { ru: ru[5], en: en[5] },
    rarity,
    category,
    purchasePrice: price,
    collectionValue: Math.round(price * 1.15),
    fixedPrice: true,
    fictional: fictional || undefined,
  }
}

export const EXPANSION_LOTS: LotDraft[] = [
  // ⌚ WATCHES — from a pocket railroad watch to the first quartz
  X('watch_casio_f91w', 'LUXURY', 'COMMON', 150, ['Casio', 'Casio'],
    ['Casio F-91W', 'с 1989', 'Лёгкие цифровые часы из пластика с подсветкой, будильником и секундомером.', 'Модель выпускается без изменений с 1989 года и стала одной из самых массовых часов в мире.', 'Коллекционируют не за цену, а за культовый дизайн цифровой эпохи.', 'В 1970-е годы электроника сделала точные часы доступными каждому. F-91W появилась в 1989 году; одной батарейки ей хватает примерно на семь лет, а корпус весит около 20 граммов.'],
    ['Casio F-91W', 'from 1989', 'A light plastic digital watch with a backlight, alarm and stopwatch.', 'The model has been made unchanged since 1989 and is one of the best-selling watches in the world.', 'Collected not for the price but for the cult design of the digital age.', 'In the 1970s electronics made accurate watches affordable to everyone. The F-91W arrived in 1989; one battery lasts about seven years and the whole watch weighs around 20 grams.']),
  X('watch_trench', 'LUXURY', 'COMMON', 240, ['неизвестный мастер', 'unattributed'],
    ['Траншейные часы', '1914–1918', 'Карманный механизм в корпусе с проволочными ушками и защитной решёткой на стекле.', 'До Первой мировой войны наручные часы считались женским украшением; на фронте мужчины перешли на них, потому что доставать карманные часы в окопе было неудобно.', 'С этих часов начался переход от кармана к запястью — главный поворот часового дела XX века.', 'Такие часы часто переделывали из карманных: к корпусу припаивали ушки для ремня, а стекло закрывали металлической решёткой от осколков. Цифры и стрелки покрывали светящейся краской с радием — о её опасности тогда ещё не знали.'],
    ['Trench watch', '1914–1918', 'A pocket movement in a case with wire lugs and a guard grille over the crystal.', 'Before the First World War wristwatches were seen as ladies’ jewellery; at the front men switched to them because pulling a pocket watch out in a trench was awkward.', 'These watches began the move from pocket to wrist — the key turn of 20th-century watchmaking.', 'Many were converted pocket watches: wire lugs were soldered on for a strap and a metal grille guarded the crystal from shrapnel. Numerals and hands were painted with radium lume, whose danger was not yet understood.']),
  X('watch_railroad', 'LUXURY', 'COMMON', 280, ['железные дороги США', 'US railroads'],
    ['Карманные часы железнодорожника', 'конец XIX — начало XX в.', 'Крупные арабские цифры, толстые стрелки и заводная головка на «12».', 'После крушения поездов в Кинтоне (Огайо) в 1891 году из-за отстававших часов американские дороги ввели строгий стандарт точности.', 'Точность, от которой зависели жизни пассажиров.', 'Стандарт требовал механизм не меньше чем на 17 камнях, регулировку в нескольких положениях и отклонение около 30 секунд в неделю. Часы проводников и машинистов регулярно сверял специальный инспектор.'],
    ['Railroad pocket watch', 'late 19th – early 20th c.', 'Large Arabic numerals, bold hands and the crown at twelve.', 'After the 1891 train collision at Kipton, Ohio, blamed on a slow watch, American railroads adopted a strict accuracy standard.', 'Precision that passengers’ lives depended on.', 'The standard demanded at least 17 jewels, adjustment to several positions and a rate of about 30 seconds a week. A watch inspector regularly checked the watches of conductors and engineers.']),
  X('watch_vostok', 'LUXURY', 'RARE', 360, ['завод «Восток», Чистополь', 'Vostok, Chistopol'],
    ['«Восток» Командирские', 'с 1960-х', 'Советские механические часы с водозащитой и звездой на циферблате.', 'Водозащита устроена необычно: давление воды само прижимает уплотнение задней крышки, поэтому корпус герметичнее на глубине.', 'Самые узнаваемые часы советской армии и доступный вход в коллекцию механики.', 'Чистопольский часовой завод в Татарстане работает с 1940-х годов. Серия «Командирские» появилась в 1960-е по заказу Министерства обороны СССР и выпускается до сих пор.'],
    ['Vostok Komandirskie', 'from the 1960s', 'Soviet mechanical watch with water resistance and a star on the dial.', 'Its water resistance is unusual: water pressure itself presses the caseback seal tighter, so the case seals better at depth.', 'The most recognisable Soviet army watch and an affordable way into mechanical collecting.', 'The Chistopol watch factory in Tatarstan has been running since the 1940s. The Komandirskie series appeared in the 1960s on an order from the USSR Ministry of Defence and is still made today.']),
  X('watch_hamilton_ventura', 'LUXURY', 'RARE', 850, ['Hamilton', 'Hamilton'],
    ['Hamilton Ventura', 'с 1957', 'Треугольный корпус-щит, похожий на космос 1950-х.', 'Одни из первых в мире наручных часов на батарейке — электрических, но ещё не кварцевых.', 'Мост между механикой и электроникой.', 'Hamilton представил Ventura в 1957 году; асимметричный корпус нарисовал дизайнер Ричард Арбиб. В фильме «Голубые Гавайи» (1961) такие часы носил Элвис Пресли.'],
    ['Hamilton Ventura', 'from 1957', 'A triangular shield case that looks like 1950s space age.', 'One of the world’s first battery-powered wristwatches — electric, but not yet quartz.', 'A bridge between mechanics and electronics.', 'Hamilton launched the Ventura in 1957; the asymmetric case was drawn by designer Richard Arbib. Elvis Presley wore one in the film Blue Hawaii (1961).']),
  X('watch_longines_lindbergh', 'LUXURY', 'RARE', 1300, ['Longines', 'Longines'],
    ['Longines Lindbergh Hour Angle', 'с 1931', 'Огромный корпус для запястья поверх лётной куртки и вращающийся безель.', 'Часы придуманы по идее Чарльза Линдберга: по ним штурман переводил время в часовой угол и находил долготу.', 'Инструмент эпохи первых перелётов через океан.', 'В 1927 году Линдберг в одиночку перелетел Атлантику без посадки. По его эскизу Longines выпустил в 1931 году часы Hour Angle, которые упрощали астрономическую навигацию в полёте.'],
    ['Longines Lindbergh Hour Angle', 'from 1931', 'A huge case to wear over a flying jacket and a rotating bezel.', 'Designed from Charles Lindbergh’s idea: a navigator used it to turn time into hour angle and find longitude.', 'An instrument of the first ocean-crossing flights.', 'In 1927 Lindbergh flew the Atlantic solo and non-stop. From his sketch Longines released the Hour Angle watch in 1931 to simplify celestial navigation in flight.']),
  X('watch_buhr', 'LUXURY', 'EPIC', 1900, ['Laco / Stowa / Wempe / A. Lange & Söhne / IWC', 'Laco / Stowa / Wempe / A. Lange & Söhne / IWC'],
    ['Штурманские часы B-Uhr', '1940-е', 'Огромный чёрный циферблат, треугольник на «12» и длинный ремень.', 'Корпус диаметром 55 мм носили поверх рукава лётной куртки.', 'Шаблон, по которому до сих пор делают почти все «пилотские» часы.', 'Beobachtungsuhr — «часы наблюдателя» — выпускали по единому стандарту пять производителей: Laco, Stowa, Wempe, A. Lange & Söhne и IWC. Точность проверяли как у хронометров, а длинный ремень позволял надеть часы поверх одежды.'],
    ['B-Uhr navigator’s watch', '1940s', 'A huge black dial, a triangle at twelve and a long strap.', 'The 55 mm case was worn over the sleeve of a flying jacket.', 'The template for almost every “pilot’s watch” made since.', 'The Beobachtungsuhr — “observation watch” — was built to one standard by five makers: Laco, Stowa, Wempe, A. Lange & Söhne and IWC. Accuracy was tested like a chronometer, and the long strap let it go over clothing.']),
  X('watch_seiko_astron', 'LUXURY', 'EPIC', 2600, ['Seiko', 'Seiko'],
    ['Seiko Quartz Astron', '1969', 'Золотой корпус и кварцевый кристалл вместо балансового колеса.', 'Первые в мире серийные кварцевые наручные часы: продажи начались 25 декабря 1969 года в Токио.', 'С них начался «кварцевый кризис», изменивший всю часовую индустрию.', 'Кварцевый кристалл Astron колеблется 8192 раза в секунду, поэтому часы точнее любой механики. Первую партию из 100 штук продавали по цене, сравнимой со стоимостью небольшого автомобиля.'],
    ['Seiko Quartz Astron', '1969', 'A gold case and a quartz crystal instead of a balance wheel.', 'The world’s first production quartz wristwatch, on sale in Tokyo from 25 December 1969.', 'It set off the “quartz crisis” that reshaped the entire watch industry.', 'The Astron’s crystal vibrates 8,192 times a second, making it more accurate than any mechanical watch. The first batch of 100 sold for about the price of a small car.']),

  // 💎 JEWELRY — earrings, bracelets, loose stones
  X('jewel_amber_brooch', 'LUXURY', 'COMMON', 150, ['Балтика', 'Baltic'],
    ['Янтарная брошь', 'XX век', 'Тёплый медовый камень в серебряной оправе.', 'Янтарь — окаменевшая смола древних деревьев; балтийскому янтарю десятки миллионов лет.', 'Внутри янтаря иногда находят насекомых, застывших ещё до появления человека.', 'Балтийский янтарь ценили ещё в древности — «Янтарный путь» вёл от Балтики к Средиземному морю. Самый знаменитый янтарный интерьер — Янтарная комната, которую прусский король подарил Петру I в 1716 году; она пропала во время Второй мировой войны.'],
    ['Amber brooch', '20th century', 'A warm honey stone in a silver mount.', 'Amber is fossilised resin from ancient trees; Baltic amber is tens of millions of years old.', 'Amber sometimes holds insects trapped long before humans existed.', 'Baltic amber was prized in antiquity — the Amber Road ran from the Baltic to the Mediterranean. The most famous amber interior, the Amber Room, was given to Peter the Great by the King of Prussia in 1716 and vanished during the Second World War.']),
  X('jewel_charm_bracelet', 'LUXURY', 'COMMON', 270, ['Британия / США', 'Britain / USA'],
    ['Браслет с шармами', 'XIX–XX вв.', 'Золотая цепочка с подвесками-воспоминаниями.', 'Королева Виктория носила браслеты с памятными медальонами и сделала их модными в Британии.', 'Каждая подвеска — отдельная история владельца, поэтому двух одинаковых браслетов не бывает.', 'Амулеты на цепочке носили ещё в древности. В XIX веке браслеты с медальонами и подвесками стали модой викторианской Англии, а в середине XX века — массовым подарком в США.'],
    ['Charm bracelet', '19th–20th c.', 'A gold chain with keepsake charms.', 'Queen Victoria wore bracelets with memorial lockets and made them fashionable in Britain.', 'Each charm is its own story, so no two bracelets are alike.', 'Amulets on a chain were worn in antiquity. In the 19th century bracelets with lockets and charms became a Victorian fashion, and by the mid-20th century a popular gift in the USA.']),
  X('jewel_girandole', 'LUXURY', 'RARE', 680, ['Европа', 'Europe'],
    ['Серьги-жирандоли', 'XVIII век', 'Три подвески-капли под бантом или розеткой.', 'Название — от итальянского girandola: так называли фонтан огней и многорожковый подсвечник.', 'Украшение, которое сверкает при каждом движении головы.', 'Жирандоли были в моде при европейских дворах XVII–XVIII веков. Под свечами камни часто ставили в закрытые оправы с фольгой — она отражала свет и усиливала блеск.'],
    ['Girandole earrings', '18th century', 'Three drop pendants under a bow or rosette.', 'The name comes from Italian girandola — a fountain of fireworks or a branched candlestick.', 'Jewellery that flashes with every turn of the head.', 'Girandoles were fashionable at European courts in the 17th–18th centuries. For candlelight, stones were often set in closed mounts backed with foil that reflected light and boosted sparkle.']),
  X('jewel_rose_cut', 'LUXURY', 'RARE', 1200, ['Европа', 'Europe'],
    ['Бриллиант огранки «роза»', 'XVII–XVIII вв.', 'Плоское основание и купол из треугольных граней.', 'Огранка «роза» появилась в XVI веке — задолго до современной круглой бриллиантовой.', 'Мягкое свечение при свечах, которое не повторяет ни одна современная огранка.', 'Современную круглую огранку с 57–58 гранями рассчитал Марсель Толковский в 1919 году. До этого огранщики берегли вес камня, а не максимальный блеск, поэтому «розы» плоские и широкие.'],
    ['Rose-cut diamond', '17th–18th c.', 'A flat base and a dome of triangular facets.', 'The rose cut appeared in the 16th century — long before the modern round brilliant.', 'A soft candlelit glow no modern cut reproduces.', 'The modern round brilliant with 57–58 facets was worked out by Marcel Tolkowsky in 1919. Before that, cutters saved the stone’s weight rather than chasing maximum sparkle, so rose cuts are flat and wide.']),
  X('jewel_opal_ring', 'LUXURY', 'EPIC', 1600, ['Австралия', 'Australia'],
    ['Кольцо с австралийским опалом', 'XX век', 'Камень, в котором вспыхивают все цвета радуги.', 'Игра цвета опала — это дифракция света на крошечных шариках кремнезёма внутри камня.', 'Двух одинаковых опалов не бывает.', 'Большую часть благородного опала в мире добывают в Австралии. Город Кубер-Педи знаменит тем, что многие его жители живут в подземных домах, спасаясь от жары.'],
    ['Australian opal ring', '20th century', 'A stone that flashes every colour of the rainbow.', 'Opal’s play of colour is light diffracting off tiny silica spheres inside the stone.', 'No two opals are alike.', 'Most of the world’s precious opal is mined in Australia. The town of Coober Pedy is famous because many residents live in underground homes to escape the heat.']),
  X('jewel_nouveau_pendant', 'LUXURY', 'EPIC', 3200, ['школа ар-нуво, Франция', 'Art Nouveau school, France'],
    ['Кулон ар-нуво «Стрекоза»', 'около 1900', 'Стрекоза в прозрачной эмали, сквозь которую светит свет.', 'Эмаль «пликажур» не имеет подложки и работает как крошечный витраж.', 'Эпоха, когда художественная идея стала дороже камня.', 'Ар-нуво расцвёл около 1890–1910 годов. Рене Лалик сочетал золото с эмалью, рогом и стеклом, и на Всемирной выставке 1900 года в Париже его украшения стали сенсацией. Этот лот — работа в стиле эпохи, не Лалика.'],
    ['Art Nouveau dragonfly pendant', 'about 1900', 'A dragonfly in translucent enamel that lets light through.', 'Plique-à-jour enamel has no backing and works like a tiny stained-glass window.', 'The age when the artistic idea became worth more than the stone.', 'Art Nouveau flourished around 1890–1910. René Lalique combined gold with enamel, horn and glass, and his jewels caused a sensation at the 1900 Paris World’s Fair. This lot is a period piece in that style, not a Lalique.']),

  // 🖼️ ART — public-domain works (the lot is an in-game collectible)
  X('art_hokusai_wave', 'ART', 'EPIC', 3300, ['Кацусика Хокусай', 'Katsushika Hokusai'],
    ['Хокусай — «Большая волна в Канагаве»', 'около 1831', 'Когтистая волна над лодками и маленькая Фудзи на горизонте.', 'Это цветная гравюра на дереве: с досок печатали тысячи оттисков, поэтому её хранят сразу многие музеи.', 'Одно из самых узнаваемых японских изображений; японская гравюра повлияла на импрессионистов.', 'Лист входит в серию «Тридцать шесть видов Фудзи». Для синего цвета Хокусай использовал берлинскую лазурь — новую импортную краску. Этот лот — оттиск, а не единственный оригинал.'],
    ['Hokusai — The Great Wave off Kanagawa', 'about 1831', 'A clawing wave over boats and a small Mount Fuji on the horizon.', 'It is a colour woodblock print: thousands of impressions were pulled, so many museums hold one.', 'One of the most recognisable Japanese images; Japanese prints influenced the Impressionists.', 'The sheet belongs to the series Thirty-six Views of Mount Fuji. For its blue Hokusai used Prussian blue, a new imported pigment. This lot is an impression, not a unique original.']),
  X('art_vangogh_sunflowers', 'ART', 'LEGENDARY', 16000, ['Винсент ван Гог', 'Vincent van Gogh'],
    ['Ван Гог — «Подсолнухи»', '1888', 'Жёлтые цветы в глиняной вазе на жёлтом фоне.', 'Ван Гог писал серию в Арле, чтобы украсить комнату для приезда друга — Поля Гогена.', 'Жёлтый стал для Ван Гога цветом радости и южного солнца.', 'Серия создана в августе 1888 года. Вариант с пятнадцатью цветками хранится в Лондонской национальной галерее; другие версии — в Амстердаме, Мюнхене, Филадельфии и Токио.'],
    ['Van Gogh — Sunflowers', '1888', 'Yellow flowers in an earthenware vase on a yellow ground.', 'Van Gogh painted the series in Arles to decorate a room for his friend Paul Gauguin’s arrival.', 'Yellow became Van Gogh’s colour of joy and southern sun.', 'The series was painted in August 1888. The fifteen-flower version is in the National Gallery, London; other versions are in Amsterdam, Munich, Philadelphia and Tokyo.']),
  X('art_turner_temeraire', 'ART', 'EPIC', 5200, ['Уильям Тёрнер', 'J. M. W. Turner'],
    ['Тёрнер — «Последний рейс корабля „Отважный“»', '1839', 'Призрачный парусник за чёрным паровым буксиром на закате.', 'Корабль «Отважный» сражался при Трафальгаре в 1805 году; на картине его тянут на разборку.', 'Картина о смене эпох: парус уступает пару.', 'Полотно хранится в Лондонской национальной галерее — Тёрнер завещал свои работы нации. В 2005 году в опросе BBC Radio 4 его назвали самой любимой картиной Британии.'],
    ['Turner — The Fighting Temeraire', '1839', 'A ghostly sailing ship behind a black steam tug at sunset.', 'HMS Temeraire fought at Trafalgar in 1805; here she is towed away to be broken up.', 'A picture about a changing age: sail gives way to steam.', 'The canvas hangs in the National Gallery, London — Turner bequeathed his works to the nation. In a 2005 BBC Radio 4 poll it was voted Britain’s favourite painting.']),
  X('art_bruegel_hunters', 'ART', 'LEGENDARY', 12000, ['Питер Брейгель Старший', 'Pieter Bruegel the Elder'],
    ['Брейгель — «Охотники на снегу»', '1565', 'Охотники с собаками спускаются с холма к замёрзшим прудам.', 'Картина из цикла о временах года; из шести полотен, по-видимому, сохранились пять.', 'Один из первых великих «чистых» пейзажей в европейской живописи.', 'Картина хранится в Музее истории искусств в Вене. Её можно узнать в фильме Андрея Тарковского «Солярис» (1972).'],
    ['Bruegel — Hunters in the Snow', '1565', 'Hunters and dogs come down a hill towards frozen ponds.', 'It belongs to a cycle of the seasons; of the six paintings, five appear to survive.', 'One of the first great landscapes in European painting.', 'The painting is in the Kunsthistorisches Museum, Vienna. It appears in Andrei Tarkovsky’s film Solaris (1972).']),

  // 🏺 ANTIQUES
  X('antique_staunton_chess', 'INTERIOR', 'RARE', 540, ['Jaques of London', 'Jaques of London'],
    ['Шахматы Стаунтона', 'с 1849', 'Фигуры из самшита и эбенового дерева в классической форме.', 'Эта форма фигур стала стандартом для официальных турниров во всём мире.', 'Узнаваемый силуэт, который сделал шахматы одинаковыми для всех игроков.', 'Дизайн зарегистрировал Натаниэль Кук в 1849 году, продвигал его сильнейший английский шахматист Говард Стаунтон, а комплекты выпускала фирма Jaques of London. До этого в разных странах фигуры сильно отличались.'],
    ['Staunton chess set', 'from 1849', 'Boxwood and ebony pieces in the classic shape.', 'This shape became the standard for official tournaments worldwide.', 'A recognisable silhouette that made chess look the same for every player.', 'The design was registered by Nathaniel Cooke in 1849, promoted by England’s leading player Howard Staunton and made by Jaques of London. Before that, pieces varied widely from country to country.']),
  X('antique_tula_samovar', 'INTERIOR', 'RARE', 460, ['Тула', 'Tula'],
    ['Тульский самовар', 'XIX век', 'Медный самовар с краном, ручками и медалями выставок.', 'В XIX веке в Туле работали десятки самоварных фабрик — отсюда поговорка «в Тулу со своим самоваром».', 'Центр русского чаепития и символ домашнего гостеприимства.', 'Вода в самоваре греется от углей в трубе внутри корпуса, а сверху ставят заварочный чайник. Клейма и выбитые на корпусе медали выставок помогают определить фабрику и год.'],
    ['Tula samovar', '19th century', 'A copper samovar with a tap, handles and exhibition medals.', 'In the 19th century dozens of samovar factories worked in Tula — hence the Russian saying “to Tula with your own samovar”.', 'The heart of Russian tea-drinking and a symbol of hospitality.', 'The water is heated by charcoal in a pipe inside the body, and the teapot sits on top. Maker’s marks and exhibition medals stamped on the body help identify the factory and year.']),
  X('antique_cobalt_net', 'INTERIOR', 'RARE', 360, ['Ленинградский фарфоровый завод', 'Leningrad Porcelain Factory'],
    ['Чашка «Кобальтовая сетка»', 'рисунок 1944 г.', 'Белый фарфор с синей сеткой и золотыми звёздочками.', 'По популярной версии, сетку подсказали заклеенные крест-накрест окна блокадного Ленинграда.', 'Один из самых узнаваемых фарфоровых узоров в России.', 'Рисунок создала художница Анна Яцкевич на Ленинградском фарфоровом заводе (ныне Императорском). В 1958 году сервиз с этим узором получил золотую медаль на Всемирной выставке в Брюсселе.'],
    ['“Cobalt Net” cup', 'pattern of 1944', 'White porcelain with a blue net and gold stars.', 'A popular story says the net was inspired by the criss-cross taped windows of besieged Leningrad.', 'One of the most recognisable porcelain patterns in Russia.', 'The pattern was created by artist Anna Yatskevich at the Leningrad (now Imperial) Porcelain Factory. In 1958 a service with it won a gold medal at the Brussels World’s Fair.']),

  // 👑 COLLECTIBLES — coins, toys, sport
  X('coin_morgan', 'SPECIAL', 'COMMON', 180, ['Монетный двор США', 'US Mint'],
    ['Серебряный доллар Моргана', '1878–1904, 1921', 'Профиль Свободы и орёл на тяжёлой серебряной монете.', 'Моделью для профиля Свободы послужила филадельфийская учительница Анна Уильямс.', 'Одна из самых популярных монет у коллекционеров США.', 'Доллар назван по имени гравёра Джорджа Моргана. Его чеканили из серебра Невады, а в 1918 году по закону Питтмана миллионы таких монет переплавили.'],
    ['Morgan silver dollar', '1878–1904, 1921', 'Liberty’s profile and an eagle on a heavy silver coin.', 'The model for Liberty was a Philadelphia teacher, Anna Williams.', 'One of the most popular coins among American collectors.', 'The dollar is named after its engraver, George Morgan. It was struck from Nevada silver, and in 1918 the Pittman Act had millions of them melted down.']),
  X('coin_denarius', 'SPECIAL', 'RARE', 380, ['Древний Рим', 'Ancient Rome'],
    ['Римский денарий', 'с ок. 211 г. до н. э.', 'Серебряная монета с профилем императора.', 'Слово живёт в названиях денег: арабский динар происходит от «денария».', 'Монета, которую держали в руках жители Римской империи.', 'Денарий чеканили из серебра, но императоры постепенно снижали его долю — к III веку н. э. монета стала почти медной. Это одна из первых хорошо задокументированных инфляций.'],
    ['Roman denarius', 'from c. 211 BC', 'A silver coin with an emperor’s profile.', 'The word lives on in money names: the Arabic dinar comes from “denarius”.', 'A coin that people across the Roman Empire actually held.', 'The denarius was struck in silver, but emperors kept lowering the silver content — by the 3rd century AD it was almost copper. It is one of the first well-documented inflations.']),
  X('coin_owl', 'SPECIAL', 'EPIC', 1700, ['Афины', 'Athens'],
    ['Афинская тетрадрахма «Сова»', 'V век до н. э.', 'Голова Афины на одной стороне и сова — на другой.', 'Монету узнавали так хорошо, что её принимали по всему Средиземноморью.', 'Одна из самых узнаваемых монет Античности.', 'Серебро для «сов» добывали на Лаврийских рудниках под Афинами. У древних греков была поговорка «везти сов в Афины» — то же, что «ехать в Тулу со своим самоваром».'],
    ['Athenian owl tetradrachm', '5th century BC', 'Athena’s head on one side and an owl on the other.', 'It was so well known that it was accepted all around the Mediterranean.', 'One of the most recognisable coins of antiquity.', 'Silver for the “owls” came from the Laurion mines near Athens. The Greeks had a saying, “bringing owls to Athens” — the same as “coals to Newcastle”.']),
  X('toy_rubik', 'SPECIAL', 'COMMON', 140, ['Эрнё Рубик', 'Ernő Rubik'],
    ['Кубик Рубика, выпуск 1980 года', '1980', 'Кубик 3×3×3 с шестью цветными гранями.', 'У кубика около 43 квинтиллионов комбинаций, но любую можно собрать не больше чем за 20 ходов.', 'Самая известная головоломка в мире.', 'Эрнё Рубик, преподаватель архитектуры из Будапешта, сделал первый кубик в 1974 году как учебную модель. Мировые продажи начались в 1980 году.'],
    ['Rubik’s Cube, 1980 issue', '1980', 'A 3×3×3 cube with six coloured faces.', 'The cube has about 43 quintillion positions, yet any can be solved in 20 moves or fewer.', 'The world’s best-known puzzle.', 'Ernő Rubik, an architecture lecturer in Budapest, made the first cube in 1974 as a teaching model. Worldwide sales began in 1980.']),
  X('toy_steiff_bear', 'SPECIAL', 'RARE', 640, ['Steiff', 'Steiff'],
    ['Плюшевый мишка Steiff', 'с 1902', 'Мишка с подвижными лапами и металлической кнопкой в ухе.', 'Английское teddy bear связано с президентом Теодором «Тедди» Рузвельтом, который в 1902 году отказался застрелить привязанного медведя на охоте.', 'Один из первых плюшевых мишек в истории игрушки.', 'Ричард Штайф создал мишку с подвижными лапами в 1902 году. С 1904 года фирменный знак Steiff — кнопка в ухе.'],
    ['Steiff teddy bear', 'from 1902', 'A jointed bear with a metal button in its ear.', 'The name teddy bear comes from President Theodore “Teddy” Roosevelt, who in 1902 refused to shoot a tethered bear on a hunt.', 'One of the first teddy bears in toy history.', 'Richard Steiff designed a jointed bear in 1902. Since 1904 Steiff’s trademark has been the button in the ear.']),
  X('sport_t206', 'SPECIAL', 'LEGENDARY', 22000, ['American Tobacco Company', 'American Tobacco Company'],
    ['Бейсбольная карточка T206 Хонус Уагнер', '1909–1911', 'Маленькая карточка с портретом бейсболиста из пачки сигарет.', 'Выпуск карточки Уагнера рано прекратили, и сохранились лишь несколько десятков экземпляров.', 'Самая знаменитая спортивная карточка в мире.', 'Серию T206 выпускала American Tobacco Company, карточки вкладывали в пачки сигарет. Хонус Уагнер — один из пяти первых игроков, введённых в Зал славы бейсбола в 1936 году.'],
    ['T206 Honus Wagner baseball card', '1909–1911', 'A small player portrait card from a cigarette pack.', 'The Wagner card was withdrawn early, and only a few dozen are known to survive.', 'The most famous sports card in the world.', 'The T206 series was issued by the American Tobacco Company in cigarette packs. Honus Wagner was one of the first five players inducted into the Baseball Hall of Fame in 1936.']),

  // 🚗 CARS — the cars that put the world on wheels
  X('car_citroen_2cv', 'CARS', 'COMMON', 220, ['Citroën', 'Citroën'],
    ['Citroën 2CV', '1948–1990', 'Гофрированный капот, складная тканевая крыша и мягкая подвеска.', 'По техническому заданию машина должна была провезти двух фермеров и корзину яиц по полю, не разбив ни одного.', 'Машина, которая сделала автомобиль доступным для французской деревни.', 'Её показали на Парижском автосалоне 1948 года. 2CV выпускали больше 40 лет почти без изменений — последняя машина сошла с конвейера в 1990 году.'],
    ['Citroën 2CV', '1948–1990', 'A corrugated bonnet, a folding canvas roof and soft suspension.', 'The brief said it had to carry two farmers and a basket of eggs across a field without breaking one.', 'The car that put rural France on wheels.', 'It was shown at the 1948 Paris Motor Show. The 2CV was built for more than 40 years with few changes — the last one left the line in 1990.']),
  X('car_fiat_500', 'CARS', 'COMMON', 260, ['Fiat', 'Fiat'],
    ['Fiat Nuova 500', '1957–1975', 'Крошечный кузов, круглые фары и складная крыша.', 'Длина машины — меньше трёх метров: её делали для тесных улиц послевоенной Италии.', 'Автомобиль, который посадил Италию за руль.', 'Конструктор — Данте Джакоза. Двухцилиндровый мотор воздушного охлаждения стоял сзади; за 18 лет выпустили около четырёх миллионов машин.'],
    ['Fiat Nuova 500', '1957–1975', 'A tiny body, round headlamps and a folding roof.', 'It is under three metres long — built for the narrow streets of postwar Italy.', 'The car that put Italy behind the wheel.', 'It was designed by Dante Giacosa. An air-cooled two-cylinder engine sat at the back; about four million were built in 18 years.']),
  X('car_mini', 'CARS', 'COMMON', 280, ['BMC', 'BMC'],
    ['Mini', 'с 1959', 'Коробочка на колёсах по углам и поперечный мотор.', 'Поперечный мотор и колёса по углам отдали большую часть длины машины салону.', 'Маленькая машина, которая выигрывала ралли.', 'Алек Иссигонис создал Mini после Суэцкого кризиса 1956 года, когда бензин стал дефицитом. Mini Cooper S выигрывал ралли Монте-Карло в 1964, 1965 и 1967 годах.'],
    ['Mini', 'from 1959', 'A little box with wheels at the corners and a transverse engine.', 'The transverse engine and corner wheels gave most of the car’s length to the cabin.', 'A small car that won rallies.', 'Alec Issigonis designed the Mini after the 1956 Suez Crisis made petrol scarce. The Mini Cooper S won the Monte Carlo Rally in 1964, 1965 and 1967.']),
  X('car_vw_beetle', 'CARS', 'RARE', 420, ['Volkswagen', 'Volkswagen'],
    ['Volkswagen Beetle', '1938–2003', 'Круглый силуэт, мотор сзади и воздушное охлаждение.', 'Всего выпустили более 21 миллиона «Жуков»; последний собрали в Мексике в 2003 году.', 'Одна из самых массовых машин в истории.', 'Конструкцию разработала команда Фердинанда Порше в 1930-е годы. Массовый выпуск начался после войны под управлением британской военной администрации, и «Жук» стал символом немецкого восстановления.'],
    ['Volkswagen Beetle', '1938–2003', 'A round silhouette, a rear engine and air cooling.', 'More than 21 million Beetles were built; the last one in Mexico in 2003.', 'One of the most-produced cars in history.', 'It was designed by Ferdinand Porsche’s team in the 1930s. Mass production began after the war under the British military administration, and the Beetle became a symbol of German recovery.']),
  X('car_ford_t', 'CARS', 'RARE', 1100, ['Ford', 'Ford'],
    ['Ford Model T', '1908–1927', 'Высокий кузов, спицевые колёса и простая надёжная механика.', 'В 1913 году Форд запустил движущийся конвейер, и сборка одной машины сократилась с полудня до примерно полутора часов.', 'Автомобиль, который сделал машину вещью для всех, а не для богатых.', 'Выпущено более 15 миллионов Model T. Фраза «любой цвет, если он чёрный» связана с годами, когда машины красили только в чёрный — по распространённому объяснению, он быстрее сох.'],
    ['Ford Model T', '1908–1927', 'A tall body, spoked wheels and simple, sturdy mechanics.', 'In 1913 Ford started a moving assembly line and building one car fell from half a day to about an hour and a half.', 'The car that made motoring for everyone, not only the rich.', 'Over 15 million Model Ts were built. “Any colour so long as it’s black” refers to the years when they were painted only black — commonly explained by black paint drying fastest.']),

  // 💰 RARE OBJECTS — DuckJackpot lore
  X('rare_cctv_tape', 'SPECIAL', 'RARE', 700, ['Легенда DuckJackpot', 'DuckJackpot lore'],
    ['Кассета камеры BANK', 'вымышленный предмет', 'Старая видеокассета с пометкой «CAM 01».', 'По легенде игры на ней записан первый рейд утки — но никто так и не смог разглядеть лицо вора.', 'Единственное «доказательство», которое так и не пригодилось охране.', 'Вымышленная история DuckJackpot: охрана BANK хранила кассету в сейфе как улику. После первого рейда кассета исчезла вместе с содержимым сейфа.'],
    ['BANK camera tape', 'fictional prop', 'An old videotape labelled “CAM 01”.', 'Game lore says it recorded the duck’s first raid — but no one could ever make out the thief’s face.', 'The only “evidence” the guards never got to use.', 'DuckJackpot fiction: BANK security kept the tape in a safe as evidence. After the first raid it vanished together with the safe’s contents.'],
    true),
  X('rare_duck_statue', 'SPECIAL', 'EPIC', 2400, ['Легенда DuckJackpot', 'DuckJackpot lore'],
    ['Золотая утка-талисман', 'вымышленный предмет', 'Статуэтка утки из золота на чёрном постаменте.', 'По легенде игры каждая банда воров держит такую утку на удачу.', 'Талисман, без которого не начинается ни один большой рейд.', 'Вымышленная история DuckJackpot: первую золотую утку отлили из монет, вынесенных из MANSION. С тех пор её копии ходят по чёрному рынку.'],
    ['Golden duck mascot', 'fictional prop', 'A gold duck statuette on a black plinth.', 'Game lore says every crew of thieves keeps one for luck.', 'A charm no big raid starts without.', 'DuckJackpot fiction: the first golden duck was cast from coins carried out of the MANSION. Copies have circulated on the black market ever since.'],
    true),
]
