import type { RaffleId } from '../constants'

/**
 * RETIRED: the 24-hour NFT try-on. NFTs are separate DuckJackpot collectibles and
 * NFT Drop prizes, not a costume for the heist duck, so gameplay no longer starts or
 * applies a trial (the MANSION vault only shows the NFT and links to the NFT Drop).
 * The skin definitions stay for reference; clearNftTrial() removes old stored trials.
 */
const KEY = 'duckjackpot.heist.nftTrial.v1'
export const NFT_TRIAL_MS = 24 * 60 * 60 * 1000

export type NftTrial = { nftId: RaffleId; startedAt: number; expiresAt: number }

const IDS: readonly RaffleId[] = ['classic', 'fast200', 'fast100']

export type NftSkinGait = 'idle' | 'walk' | 'run' | 'sneak' | 'dash'

/**
 * How an NFT dresses the heist duck (cosmetic only: no speed, loot, stealth or
 * bag bonus). The chain is:
 *
 *   NFT id → skin definition → sprite sheet → animation frames → aura / crown
 *          → dash effect → optional particles
 *
 * A sheet uses the exact grid of /heist/duck_sheet.png (4×4 frames of 256 px:
 * idle 0-3, walk 4-11, dash 12-15) so pivot, feet, scale and hitbox never
 * change. Sheets live in /public/heist/nft-skins/<folder>/sheet.png and are
 * generated by frontend/scripts/build_nft_skins.py. A new NFT is one more
 * entry here plus its sheet — no engine change.
 *
 * Fallback: if a sheet is missing or fails to load, the normal DuckJackpot
 * duck is shown with the fallback crown + aura in the skin's colour.
 */
export type NftSkinDef = {
  id: RaffleId
  /** Name on the HUB line and the try-on banner. */
  name: string
  /** Accent for aura, fallback crown and the HUB line. */
  color: number
  css: string
  /** Full-body sprite sheet (crown, shades and chain are drawn into it). Absent → normal duck. */
  sheet?: { url: string; frameWidth: number; frameHeight: number }
  /** Frame ranges on `sheet`; a missing gait falls back to the normal duck animation. */
  anims?: Partial<Record<NftSkinGait, { start: number; end: number; fps: number }>>
  /** Soft glow under the duck in `color`; `flicker` gives it faint electric pulses. */
  aura: false | { alpha: number; size: number; flicker?: boolean }
  /** Crown image over the normal duck — used only when no sheet is loaded. */
  crown: boolean
  /** Short trail drawn only while DASH is active and gone right after it. */
  dash?: { style: 'electric' | 'streak'; colors: readonly number[] }
  /** A few small sparks drifting up around the duck (hard-capped, pooled). */
  particles?: { color: number; max: number; everyMs: number }
  /** Reserved for later accessories/effects. */
  effects?: readonly string[]
}

/** Same frame layout as the normal duck (see createActorAnims in Actors.ts). */
const DUCK_GRID_ANIMS: NonNullable<NftSkinDef['anims']> = {
  idle: { start: 0, end: 3, fps: 4 },
  walk: { start: 4, end: 11, fps: 9 },
  run: { start: 4, end: 11, fps: 9 },
  sneak: { start: 4, end: 11, fps: 5 },
  dash: { start: 12, end: 15, fps: 11 },
}

function sheet(folder: string): NonNullable<NftSkinDef['sheet']> {
  return { url: `/heist/nft-skins/${folder}/sheet.png`, frameWidth: 256, frameHeight: 256 }
}

/** NFT_GOLD, NFT_FAST_200, NFT_FAST_100 — keyed by the NFT Drop id they belong to. */
export const NFT_SKINS: Record<RaffleId, NftSkinDef> = {
  // DUCK JACKPOT / GOLD — flagship: black + gold + amber, soft gold aura, rare gold sparks.
  classic: {
    id: 'classic',
    name: 'DUCK JACKPOT GOLD',
    color: 0xffd65a,
    css: '#ffd65a',
    sheet: sheet('gold'),
    anims: DUCK_GRID_ANIMS,
    aura: { alpha: 0.3, size: 132 },
    crown: true,
    particles: { color: 0xffd65a, max: 5, everyMs: 520 },
  },
  // FAST 200 — gold + orange + electric amber, faint electric aura, electric dash trail.
  fast200: {
    id: 'fast200',
    name: 'FAST 200',
    color: 0xffa834,
    css: '#ffb347',
    sheet: sheet('fast200'),
    anims: DUCK_GRID_ANIMS,
    aura: { alpha: 0.26, size: 126, flicker: true },
    crown: true,
    dash: { style: 'electric', colors: [0xffc23a, 0xff8a1a] },
  },
  // FAST 100 — black + gold + red/orange, thin red-gold aura, red-gold dash streak.
  fast100: {
    id: 'fast100',
    name: 'FAST 100',
    color: 0xff5a3a,
    css: '#ff6a4a',
    sheet: sheet('fast100'),
    anims: DUCK_GRID_ANIMS,
    aura: { alpha: 0.24, size: 120 },
    crown: true,
    dash: { style: 'streak', colors: [0xff3a2a, 0xffc440] },
  },
}

export function nftSkin(id: RaffleId): NftSkinDef {
  return NFT_SKINS[id]
}

/** Active trial or null. An expired trial is removed on read. */
export function loadNftTrial(now = Date.now()): NftTrial | null {
  try {
    const raw = localStorage.getItem(KEY)
    if (!raw) return null
    const p = JSON.parse(raw) as Partial<NftTrial>
    const nftId = IDS.find((id) => id === p.nftId)
    const startedAt = Number(p.startedAt)
    const expiresAt = Number(p.expiresAt)
    if (!nftId || !Number.isFinite(startedAt) || !Number.isFinite(expiresAt)) return null
    if (now >= expiresAt) {
      localStorage.removeItem(KEY)
      return null
    }
    return { nftId, startedAt, expiresAt }
  } catch {
    return null
  }
}

export function startNftTrial(nftId: RaffleId, now = Date.now()): NftTrial {
  const trial: NftTrial = { nftId, startedAt: now, expiresAt: now + NFT_TRIAL_MS }
  try {
    localStorage.setItem(KEY, JSON.stringify(trial))
  } catch {
    /* storage unavailable: the try-on lasts for this session only */
  }
  return trial
}

/** "23:59" style remaining time; "23:41:12" with seconds. */
export function nftTrialLeft(trial: NftTrial, now = Date.now(), seconds = false) {
  // Rounded up, so a fresh try-on reads 24:00 and "00:00" only appears at the very end.
  const ms = Math.max(0, trial.expiresAt - now)
  if (seconds) {
    const total = Math.ceil(ms / 1000)
    const h = Math.floor(total / 3600)
    const m = Math.floor((total % 3600) / 60)
    return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:${String(total % 60).padStart(2, '0')}`
  }
  const total = Math.ceil(ms / 60_000)
  return `${String(Math.floor(total / 60)).padStart(2, '0')}:${String(total % 60).padStart(2, '0')}`
}

/** Remove a trial stored by an earlier build (the try-on no longer exists in gameplay). */
export function clearNftTrial() {
  try {
    localStorage.removeItem(KEY)
  } catch {
    /* storage unavailable: nothing stored */
  }
}
