import type { GrandLevelId } from '../../heistLevel'
import type { DuckCoinKind } from '../../coinAssets'
import type { LevelDef } from './LevelDef'
import { buildGrandLevel, type GrandRoom, type GrandSpec } from './grand'

/*
 * LEVEL 3 PRIVATE BANK (50) → LEVEL 4 BLACK MARKET (60) → LEVEL 5 GRAND VAULT (70).
 * Each step: more floors, more of the door column locked, more and richer
 * safes, a denser camera net and a few more patrols — never a wall of guards.
 */

function hashN(i: number, seed: number) {
  let h = (i * 73856093) ^ (seed * 19349663)
  h = Math.imul(h ^ (h >>> 13), 1274126177)
  return ((h ^ (h >>> 16)) >>> 0) / 0xffffffff
}

/** Loot curve: pocket change at the door, fortunes at the bottom; full-width halls carry a bit more. */
function lootCurve(base: { c50: [number, number]; c100: [number, number]; finale: [number, number] }, zones: number, seed: number) {
  return (i: number, d: number): [number, number, number, number] => {
    const idx = i % 10
    const big = idx === 0 || idx === 9 ? 1.3 : 1
    const n = hashN(i, seed) - 0.5
    const c5 = Math.max(1, Math.round((6 - 2.5 * d + n) * big))
    const c10 = Math.max(1, Math.round((4 + 2 * d - n) * big))
    let c50 = Math.max(0, Math.round((base.c50[0] + base.c50[1] * d + n) * big))
    let c100 = Math.max(0, Math.round((base.c100[0] + base.c100[1] * d - n) * big))
    if (i === zones - 1) {
      c50 += base.finale[0]
      c100 += base.finale[1]
    }
    return [c5, c10, c50, c100]
  }
}

type SafeRow = [number, number, DuckCoinKind]
const safes = (rows: SafeRow[]) => rows.map(([zone, reward, extra]) => ({ zone, reward, extra }))

const L3_ROOMS: GrandRoom[] = [
  { key: 'heistL3z1', kit: 'lobby', floor: 'marble', light: 'warm' },
  { key: 'heistL3z2', kit: 'checkpoint', floor: 'tiles', light: 'cool' },
  { key: 'heistL3z3', kit: 'reception', floor: 'glass', light: 'cool' },
  { key: 'heistL3z4', kit: 'atrium', floor: 'marbleWhite', light: 'warm' },
  { key: 'heistL3z5', kit: 'lounge', floor: 'carpetBlue', light: 'warm' },
  { key: 'heistL3z6', kit: 'guardPost', floor: 'steel', light: 'blue' },
  { key: 'heistL3z7', kit: 'cashHall', floor: 'marble', light: 'warm' },
  { key: 'heistL3z8', kit: 'deposit', floor: 'vault', light: 'gold' },
  { key: 'heistL3z9', kit: 'corridor', floor: 'tiles', light: 'dim' },
  { key: 'heistL3z10', kit: 'stairs', floor: 'glass', light: 'cool' },
  { key: 'heistL3z11', kit: 'atrium', floor: 'marbleWhite', light: 'gold' },
  { key: 'heistL3z12', kit: 'office', floor: 'wood', light: 'warm' },
  { key: 'heistL3z13', kit: 'lounge', floor: 'carpetBlue', light: 'warm' },
  { key: 'heistL3z14', kit: 'office', floor: 'glass', light: 'cool' },
  { key: 'heistL3z15', kit: 'lounge', floor: 'wood', light: 'dim' },
  { key: 'heistL3z16', kit: 'deposit', floor: 'vault', light: 'gold' },
  { key: 'heistL3z17', kit: 'gallery', floor: 'glass', light: 'cool' },
  { key: 'heistL3z18', kit: 'archive', floor: 'carpetBlue', light: 'dim' },
  { key: 'heistL3z19', kit: 'cashHall', floor: 'gold', light: 'gold' },
  { key: 'heistL3z20', kit: 'stairs', floor: 'glass', light: 'cool' },
  { key: 'heistL3z21', kit: 'openOffice', floor: 'carpetBlue', light: 'cool' },
  { key: 'heistL3z22', kit: 'boardroom', floor: 'wood', light: 'warm' },
  { key: 'heistL3z23', kit: 'openOffice', floor: 'carpetBlue', light: 'cool' },
  { key: 'heistL3z24', kit: 'office', floor: 'wood', light: 'warm' },
  { key: 'heistL3z25', kit: 'archive', floor: 'carpetBlue', light: 'dim' },
  { key: 'heistL3z26', kit: 'office', floor: 'glass', light: 'cool' },
  { key: 'heistL3z27', kit: 'archive', floor: 'tiles', light: 'dim' },
  { key: 'heistL3z28', kit: 'safeRoom', floor: 'vault', light: 'gold' },
  { key: 'heistL3z29', kit: 'lounge', floor: 'glass', light: 'cool' },
  { key: 'heistL3z30', kit: 'stairs', floor: 'marbleWhite', light: 'warm' },
  { key: 'heistL3z31', kit: 'control', floor: 'steel', light: 'blue' },
  { key: 'heistL3z32', kit: 'server', floor: 'server', light: 'blue' },
  { key: 'heistL3z33', kit: 'server', floor: 'steel', light: 'cool' },
  { key: 'heistL3z34', kit: 'control', floor: 'steel', light: 'blue' },
  { key: 'heistL3z35', kit: 'safeRoom', floor: 'server', light: 'blue' },
  { key: 'heistL3z36', kit: 'corridor', floor: 'steel', light: 'dim' },
  { key: 'heistL3z37', kit: 'laser', floor: 'glass', light: 'blue' },
  { key: 'heistL3z38', kit: 'control', floor: 'steel', light: 'blue' },
  { key: 'heistL3z39', kit: 'server', floor: 'server', light: 'blue' },
  { key: 'heistL3z40', kit: 'stairs', floor: 'steel', light: 'cool' },
  { key: 'heistL3z41', kit: 'atrium', floor: 'vault', light: 'gold' },
  { key: 'heistL3z42', kit: 'bullion', floor: 'gold', light: 'gold' },
  { key: 'heistL3z43', kit: 'vaultRow', floor: 'vault', light: 'gold' },
  { key: 'heistL3z44', kit: 'jewels', floor: 'marbleWhite', light: 'gold' },
  { key: 'heistL3z45', kit: 'vaultRow', floor: 'vault', light: 'dim' },
  { key: 'heistL3z46', kit: 'laser', floor: 'steel', light: 'blue' },
  { key: 'heistL3z47', kit: 'bullion', floor: 'gold', light: 'gold' },
  { key: 'heistL3z48', kit: 'safeRoom', floor: 'vault', light: 'gold' },
  { key: 'heistL3z49', kit: 'maze', floor: 'steel', light: 'cool' },
  { key: 'heistL3z50', kit: 'finale', floor: 'gold', light: 'gold' },
]

const L4_ROOMS: GrandRoom[] = [
  { key: 'heistL4z1', kit: 'lobby', floor: 'bunker', light: 'dim' },
  { key: 'heistL4z2', kit: 'reception', floor: 'wood', light: 'warm' },
  { key: 'heistL4z3', kit: 'corridor', floor: 'carpetRed', light: 'warm' },
  { key: 'heistL4z4', kit: 'checkpoint', floor: 'bunker', light: 'dim' },
  { key: 'heistL4z5', kit: 'lounge', floor: 'wood', light: 'dim' },
  { key: 'heistL4z6', kit: 'guardPost', floor: 'concrete', light: 'cool' },
  { key: 'heistL4z7', kit: 'bar', floor: 'wood', light: 'warm' },
  { key: 'heistL4z8', kit: 'casino', floor: 'carpetRed', light: 'warm' },
  { key: 'heistL4z9', kit: 'corridor', floor: 'mansionStone', light: 'dim' },
  { key: 'heistL4z10', kit: 'stairs', floor: 'bunker', light: 'dim' },
  { key: 'heistL4z11', kit: 'lounge', floor: 'carpetRed', light: 'warm' },
  { key: 'heistL4z12', kit: 'gallery', floor: 'wood', light: 'gold' },
  { key: 'heistL4z13', kit: 'casino', floor: 'carpetRed', light: 'warm' },
  { key: 'heistL4z14', kit: 'lounge', floor: 'carpetRed', light: 'dim' },
  { key: 'heistL4z15', kit: 'cellar', floor: 'mansionStone', light: 'dim' },
  { key: 'heistL4z16', kit: 'office', floor: 'wood', light: 'warm' },
  { key: 'heistL4z17', kit: 'jewels', floor: 'marbleWhite', light: 'gold' },
  { key: 'heistL4z18', kit: 'gallery', floor: 'carpetRed', light: 'dim' },
  { key: 'heistL4z19', kit: 'casino', floor: 'ballroom', light: 'gold' },
  { key: 'heistL4z20', kit: 'stairs', floor: 'carpetRed', light: 'warm' },
  { key: 'heistL4z21', kit: 'bunker', floor: 'bunker', light: 'dim' },
  { key: 'heistL4z22', kit: 'bunker', floor: 'concrete', light: 'dim' },
  { key: 'heistL4z23', kit: 'crates', floor: 'storage', light: 'dim' },
  { key: 'heistL4z24', kit: 'crates', floor: 'storage', light: 'dim' },
  { key: 'heistL4z25', kit: 'lab', floor: 'concrete', light: 'cool' },
  { key: 'heistL4z26', kit: 'lab', floor: 'tiles', light: 'cool' },
  { key: 'heistL4z27', kit: 'crates', floor: 'steel', light: 'cool' },
  { key: 'heistL4z28', kit: 'secret', floor: 'mansionStone', light: 'dim' },
  { key: 'heistL4z29', kit: 'crates', floor: 'steel', light: 'dim' },
  { key: 'heistL4z30', kit: 'stairs', floor: 'bunker', light: 'dim' },
  { key: 'heistL4z31', kit: 'barracks', floor: 'concrete', light: 'dim' },
  { key: 'heistL4z32', kit: 'control', floor: 'steel', light: 'blue' },
  { key: 'heistL4z33', kit: 'laser', floor: 'bunker', light: 'dim' },
  { key: 'heistL4z34', kit: 'control', floor: 'steel', light: 'blue' },
  { key: 'heistL4z35', kit: 'server', floor: 'server', light: 'blue' },
  { key: 'heistL4z36', kit: 'office', floor: 'steel', light: 'cool' },
  { key: 'heistL4z37', kit: 'control', floor: 'bunker', light: 'dim' },
  { key: 'heistL4z38', kit: 'maze', floor: 'steel', light: 'dim' },
  { key: 'heistL4z39', kit: 'checkpoint', floor: 'steel', light: 'cool' },
  { key: 'heistL4z40', kit: 'stairs', floor: 'bunker', light: 'dim' },
  { key: 'heistL4z41', kit: 'vaultRow', floor: 'vault', light: 'gold' },
  { key: 'heistL4z42', kit: 'collection', floor: 'vault', light: 'gold' },
  { key: 'heistL4z43', kit: 'collection', floor: 'mansionStone', light: 'dim' },
  { key: 'heistL4z44', kit: 'jewels', floor: 'vault', light: 'gold' },
  { key: 'heistL4z45', kit: 'jewels', floor: 'marbleWhite', light: 'gold' },
  { key: 'heistL4z46', kit: 'bullion', floor: 'vault', light: 'gold' },
  { key: 'heistL4z47', kit: 'gallery', floor: 'vault', light: 'dim' },
  { key: 'heistL4z48', kit: 'safeRoom', floor: 'vault', light: 'dim' },
  { key: 'heistL4z49', kit: 'secret', floor: 'mansionStone', light: 'dim' },
  { key: 'heistL4z50', kit: 'stairs', floor: 'vault', light: 'gold' },
  { key: 'heistL4z51', kit: 'maze', floor: 'bunker', light: 'dim' },
  { key: 'heistL4z52', kit: 'archive', floor: 'wood', light: 'dim' },
  { key: 'heistL4z53', kit: 'bullion', floor: 'gold', light: 'gold' },
  { key: 'heistL4z54', kit: 'jewels', floor: 'marbleWhite', light: 'gold' },
  { key: 'heistL4z55', kit: 'office', floor: 'carpetRed', light: 'warm' },
  { key: 'heistL4z56', kit: 'treasury', floor: 'gold', light: 'gold' },
  { key: 'heistL4z57', kit: 'collection', floor: 'gold', light: 'gold' },
  { key: 'heistL4z58', kit: 'guardPost', floor: 'steel', light: 'blue' },
  { key: 'heistL4z59', kit: 'maze', floor: 'vault', light: 'cool' },
  { key: 'heistL4z60', kit: 'finale', floor: 'gold', light: 'gold' },
]

const L5_ROOMS: GrandRoom[] = [
  { key: 'heistL5z1', kit: 'lobby', floor: 'blackMarble', light: 'gold' },
  { key: 'heistL5z2', kit: 'reception', floor: 'gold', light: 'gold' },
  { key: 'heistL5z3', kit: 'atrium', floor: 'blackMarble', light: 'warm' },
  { key: 'heistL5z4', kit: 'fountain', floor: 'blackMarble', light: 'gold' },
  { key: 'heistL5z5', kit: 'reception', floor: 'carpetRed', light: 'warm' },
  { key: 'heistL5z6', kit: 'guardPost', floor: 'blackMarble', light: 'cool' },
  { key: 'heistL5z7', kit: 'corridor', floor: 'marbleWhite', light: 'warm' },
  { key: 'heistL5z8', kit: 'fountain', floor: 'blackMarble', light: 'gold' },
  { key: 'heistL5z9', kit: 'corridor', floor: 'carpetRed', light: 'warm' },
  { key: 'heistL5z10', kit: 'stairs', floor: 'blackMarble', light: 'gold' },
  { key: 'heistL5z11', kit: 'atrium', floor: 'gold', light: 'gold' },
  { key: 'heistL5z12', kit: 'lounge', floor: 'ballroom', light: 'gold' },
  { key: 'heistL5z13', kit: 'casino', floor: 'carpetRed', light: 'gold' },
  { key: 'heistL5z14', kit: 'casino', floor: 'ballroom', light: 'warm' },
  { key: 'heistL5z15', kit: 'bullion', floor: 'gold', light: 'gold' },
  { key: 'heistL5z16', kit: 'lounge', floor: 'carpetRed', light: 'warm' },
  { key: 'heistL5z17', kit: 'library', floor: 'wood', light: 'warm' },
  { key: 'heistL5z18', kit: 'library', floor: 'wood', light: 'gold' },
  { key: 'heistL5z19', kit: 'safeRoom', floor: 'gold', light: 'gold' },
  { key: 'heistL5z20', kit: 'stairs', floor: 'gold', light: 'gold' },
  { key: 'heistL5z21', kit: 'collection', floor: 'blackMarble', light: 'gold' },
  { key: 'heistL5z22', kit: 'atrium', floor: 'marbleWhite', light: 'warm' },
  { key: 'heistL5z23', kit: 'gallery', floor: 'parquet', light: 'warm' },
  { key: 'heistL5z24', kit: 'jewels', floor: 'blackMarble', light: 'gold' },
  { key: 'heistL5z25', kit: 'collection', floor: 'wood', light: 'warm' },
  { key: 'heistL5z26', kit: 'jewels', floor: 'marbleWhite', light: 'gold' },
  { key: 'heistL5z27', kit: 'bullion', floor: 'vault', light: 'gold' },
  { key: 'heistL5z28', kit: 'safeRoom', floor: 'vault', light: 'gold' },
  { key: 'heistL5z29', kit: 'secret', floor: 'carpetRed', light: 'dim' },
  { key: 'heistL5z30', kit: 'stairs', floor: 'blackMarble', light: 'gold' },
  { key: 'heistL5z31', kit: 'control', floor: 'steel', light: 'blue' },
  { key: 'heistL5z32', kit: 'control', floor: 'steel', light: 'blue' },
  { key: 'heistL5z33', kit: 'laser', floor: 'blackMarble', light: 'blue' },
  { key: 'heistL5z34', kit: 'laser', floor: 'steel', light: 'blue' },
  { key: 'heistL5z35', kit: 'barracks', floor: 'steel', light: 'cool' },
  { key: 'heistL5z36', kit: 'checkpoint', floor: 'steel', light: 'blue' },
  { key: 'heistL5z37', kit: 'laser', floor: 'glass', light: 'blue' },
  { key: 'heistL5z38', kit: 'maze', floor: 'vault', light: 'dim' },
  { key: 'heistL5z39', kit: 'secret', floor: 'blackMarble', light: 'dim' },
  { key: 'heistL5z40', kit: 'stairs', floor: 'steel', light: 'cool' },
  { key: 'heistL5z41', kit: 'vaultRow', floor: 'vault', light: 'gold' },
  { key: 'heistL5z42', kit: 'maze', floor: 'steel', light: 'dim' },
  { key: 'heistL5z43', kit: 'vaultRow', floor: 'vault', light: 'gold' },
  { key: 'heistL5z44', kit: 'bullion', floor: 'marbleWhite', light: 'cool' },
  { key: 'heistL5z45', kit: 'maze', floor: 'vault', light: 'dim' },
  { key: 'heistL5z46', kit: 'deposit', floor: 'vault', light: 'gold' },
  { key: 'heistL5z47', kit: 'jewels', floor: 'mansionStone', light: 'gold' },
  { key: 'heistL5z48', kit: 'safeRoom', floor: 'vault', light: 'gold' },
  { key: 'heistL5z49', kit: 'corridor', floor: 'steel', light: 'dim' },
  { key: 'heistL5z50', kit: 'stairs', floor: 'vault', light: 'gold' },
  { key: 'heistL5z51', kit: 'treasury', floor: 'gold', light: 'gold' },
  { key: 'heistL5z52', kit: 'bullion', floor: 'gold', light: 'gold' },
  { key: 'heistL5z53', kit: 'lab', floor: 'steel', light: 'gold' },
  { key: 'heistL5z54', kit: 'lab', floor: 'gold', light: 'gold' },
  { key: 'heistL5z55', kit: 'office', floor: 'blackMarble', light: 'gold' },
  { key: 'heistL5z56', kit: 'vaultRow', floor: 'marbleWhite', light: 'cool' },
  { key: 'heistL5z57', kit: 'archive', floor: 'wood', light: 'gold' },
  { key: 'heistL5z58', kit: 'safeRoom', floor: 'gold', light: 'gold' },
  { key: 'heistL5z59', kit: 'maze', floor: 'blackMarble', light: 'gold' },
  { key: 'heistL5z60', kit: 'stairs', floor: 'gold', light: 'gold' },
  { key: 'heistL5z61', kit: 'atrium', floor: 'blackMarble', light: 'gold' },
  { key: 'heistL5z62', kit: 'corridor', floor: 'gold', light: 'gold' },
  { key: 'heistL5z63', kit: 'treasury', floor: 'gold', light: 'gold' },
  { key: 'heistL5z64', kit: 'jewels', floor: 'blackMarble', light: 'gold' },
  { key: 'heistL5z65', kit: 'bullion', floor: 'gold', light: 'gold' },
  { key: 'heistL5z66', kit: 'treasury', floor: 'blackMarble', light: 'gold' },
  { key: 'heistL5z67', kit: 'guardPost', floor: 'blackMarble', light: 'blue' },
  { key: 'heistL5z68', kit: 'treasury', floor: 'gold', light: 'gold' },
  { key: 'heistL5z69', kit: 'maze', floor: 'blackMarble', light: 'gold' },
  { key: 'heistL5z70', kit: 'finale', floor: 'gold', light: 'gold' },
]

const L6_ROOMS: GrandRoom[] = [
  { key: 'heistL6z1', kit: 'lobby', floor: 'skyline', light: 'cool' },
  { key: 'heistL6z2', kit: 'checkpoint', floor: 'steel', light: 'cool' },
  { key: 'heistL6z3', kit: 'reception', floor: 'skyline', light: 'warm' },
  { key: 'heistL6z4', kit: 'atrium', floor: 'glass', light: 'cool' },
  { key: 'heistL6z5', kit: 'lounge', floor: 'carpetBlue', light: 'warm' },
  { key: 'heistL6z6', kit: 'guardPost', floor: 'steel', light: 'blue' },
  { key: 'heistL6z7', kit: 'corridor', floor: 'skyline', light: 'cool' },
  { key: 'heistL6z8', kit: 'archive', floor: 'tiles', light: 'dim' },
  { key: 'heistL6z9', kit: 'corridor', floor: 'steel', light: 'dim' },
  { key: 'heistL6z10', kit: 'stairs', floor: 'skyline', light: 'cool' },
  { key: 'heistL6z11', kit: 'openOffice', floor: 'carpetBlue', light: 'cool' },
  { key: 'heistL6z12', kit: 'boardroom', floor: 'glass', light: 'cool' },
  { key: 'heistL6z13', kit: 'bar', floor: 'wood', light: 'warm' },
  { key: 'heistL6z14', kit: 'archive', floor: 'tiles', light: 'dim' },
  { key: 'heistL6z15', kit: 'office', floor: 'carpetBlue', light: 'warm' },
  { key: 'heistL6z16', kit: 'gallery', floor: 'skyline', light: 'cool' },
  { key: 'heistL6z17', kit: 'lounge', floor: 'carpetBlue', light: 'dim' },
  { key: 'heistL6z18', kit: 'crates', floor: 'storage', light: 'dim' },
  { key: 'heistL6z19', kit: 'lounge', floor: 'wood', light: 'warm' },
  { key: 'heistL6z20', kit: 'stairs', floor: 'skyline', light: 'cool' },
  { key: 'heistL6z21', kit: 'openOffice', floor: 'carpetBlue', light: 'cool' },
  { key: 'heistL6z22', kit: 'control', floor: 'steel', light: 'blue' },
  { key: 'heistL6z23', kit: 'office', floor: 'glass', light: 'cool' },
  { key: 'heistL6z24', kit: 'openOffice', floor: 'carpetBlue', light: 'cool' },
  { key: 'heistL6z25', kit: 'boardroom', floor: 'wood', light: 'warm' },
  { key: 'heistL6z26', kit: 'office', floor: 'glass', light: 'cool' },
  { key: 'heistL6z27', kit: 'control', floor: 'steel', light: 'blue' },
  { key: 'heistL6z28', kit: 'archive', floor: 'carpetBlue', light: 'dim' },
  { key: 'heistL6z29', kit: 'office', floor: 'steel', light: 'dim' },
  { key: 'heistL6z30', kit: 'stairs', floor: 'skyline', light: 'cool' },
  { key: 'heistL6z31', kit: 'server', floor: 'server', light: 'blue' },
  { key: 'heistL6z32', kit: 'server', floor: 'steel', light: 'cool' },
  { key: 'heistL6z33', kit: 'server', floor: 'server', light: 'blue' },
  { key: 'heistL6z34', kit: 'control', floor: 'steel', light: 'blue' },
  { key: 'heistL6z35', kit: 'server', floor: 'server', light: 'blue' },
  { key: 'heistL6z36', kit: 'lab', floor: 'steel', light: 'cool' },
  { key: 'heistL6z37', kit: 'corridor', floor: 'steel', light: 'blue' },
  { key: 'heistL6z38', kit: 'safeRoom', floor: 'server', light: 'blue' },
  { key: 'heistL6z39', kit: 'control', floor: 'steel', light: 'blue' },
  { key: 'heistL6z40', kit: 'stairs', floor: 'steel', light: 'cool' },
  { key: 'heistL6z41', kit: 'atrium', floor: 'skyline', light: 'warm' },
  { key: 'heistL6z42', kit: 'office', floor: 'wood', light: 'warm' },
  { key: 'heistL6z43', kit: 'boardroom', floor: 'wood', light: 'warm' },
  { key: 'heistL6z44', kit: 'archive', floor: 'carpetBlue', light: 'dim' },
  { key: 'heistL6z45', kit: 'bar', floor: 'wood', light: 'warm' },
  { key: 'heistL6z46', kit: 'safeRoom', floor: 'vault', light: 'gold' },
  { key: 'heistL6z47', kit: 'gallery', floor: 'skyline', light: 'warm' },
  { key: 'heistL6z48', kit: 'reception', floor: 'carpetBlue', light: 'warm' },
  { key: 'heistL6z49', kit: 'boardroom', floor: 'glass', light: 'cool' },
  { key: 'heistL6z50', kit: 'stairs', floor: 'skyline', light: 'warm' },
  { key: 'heistL6z51', kit: 'lounge', floor: 'carpetRed', light: 'warm' },
  { key: 'heistL6z52', kit: 'lounge', floor: 'wood', light: 'dim' },
  { key: 'heistL6z53', kit: 'library', floor: 'wood', light: 'warm' },
  { key: 'heistL6z54', kit: 'casino', floor: 'carpetRed', light: 'warm' },
  { key: 'heistL6z55', kit: 'bar', floor: 'glass', light: 'cool' },
  { key: 'heistL6z56', kit: 'lounge', floor: 'carpetBlue', light: 'dim' },
  { key: 'heistL6z57', kit: 'fountain', floor: 'skyline', light: 'cool' },
  { key: 'heistL6z58', kit: 'collection', floor: 'marbleWhite', light: 'gold' },
  { key: 'heistL6z59', kit: 'cellar', floor: 'mansionStone', light: 'dim' },
  { key: 'heistL6z60', kit: 'stairs', floor: 'skyline', light: 'warm' },
  { key: 'heistL6z61', kit: 'atrium', floor: 'marbleWhite', light: 'gold' },
  { key: 'heistL6z62', kit: 'office', floor: 'wood', light: 'warm' },
  { key: 'heistL6z63', kit: 'lounge', floor: 'glass', light: 'cool' },
  { key: 'heistL6z64', kit: 'lounge', floor: 'carpetRed', light: 'warm' },
  { key: 'heistL6z65', kit: 'collection', floor: 'marbleWhite', light: 'gold' },
  { key: 'heistL6z66', kit: 'jewels', floor: 'marbleWhite', light: 'gold' },
  { key: 'heistL6z67', kit: 'gallery', floor: 'skyline', light: 'warm' },
  { key: 'heistL6z68', kit: 'safeRoom', floor: 'vault', light: 'gold' },
  { key: 'heistL6z69', kit: 'barracks', floor: 'steel', light: 'cool' },
  { key: 'heistL6z70', kit: 'stairs', floor: 'marbleWhite', light: 'gold' },
  { key: 'heistL6z71', kit: 'fountain', floor: 'skyline', light: 'cool' },
  { key: 'heistL6z72', kit: 'lounge', floor: 'steel', light: 'cool' },
  { key: 'heistL6z73', kit: 'fountain', floor: 'greenhouse', light: 'cool' },
  { key: 'heistL6z74', kit: 'atrium', floor: 'glass', light: 'cool' },
  { key: 'heistL6z75', kit: 'control', floor: 'steel', light: 'blue' },
  { key: 'heistL6z76', kit: 'safeRoom', floor: 'vault', light: 'gold' },
  { key: 'heistL6z77', kit: 'corridor', floor: 'skyline', light: 'cool' },
  { key: 'heistL6z78', kit: 'guardPost', floor: 'steel', light: 'blue' },
  { key: 'heistL6z79', kit: 'treasury', floor: 'gold', light: 'gold' },
  { key: 'heistL6z80', kit: 'finale', floor: 'gold', light: 'gold' },
]

const L7_ROOMS: GrandRoom[] = [
  { key: 'heistL7z1', kit: 'lobby', floor: 'neon', light: 'dim' },
  { key: 'heistL7z2', kit: 'bar', floor: 'neon', light: 'warm' },
  { key: 'heistL7z3', kit: 'checkpoint', floor: 'bunker', light: 'cool' },
  { key: 'heistL7z4', kit: 'crates', floor: 'neon', light: 'warm' },
  { key: 'heistL7z5', kit: 'bar', floor: 'tiles', light: 'warm' },
  { key: 'heistL7z6', kit: 'guardPost', floor: 'bunker', light: 'blue' },
  { key: 'heistL7z7', kit: 'crates', floor: 'neon', light: 'warm' },
  { key: 'heistL7z8', kit: 'cashHall', floor: 'wood', light: 'warm' },
  { key: 'heistL7z9', kit: 'corridor', floor: 'bunker', light: 'dim' },
  { key: 'heistL7z10', kit: 'stairs', floor: 'neon', light: 'dim' },
  { key: 'heistL7z11', kit: 'corridor', floor: 'neon', light: 'warm' },
  { key: 'heistL7z12', kit: 'jewels', floor: 'neon', light: 'gold' },
  { key: 'heistL7z13', kit: 'cashHall', floor: 'neon', light: 'gold' },
  { key: 'heistL7z14', kit: 'casino', floor: 'carpetRed', light: 'dim' },
  { key: 'heistL7z15', kit: 'office', floor: 'wood', light: 'dim' },
  { key: 'heistL7z16', kit: 'jewels', floor: 'neon', light: 'gold' },
  { key: 'heistL7z17', kit: 'lounge', floor: 'neon', light: 'warm' },
  { key: 'heistL7z18', kit: 'archive', floor: 'wood', light: 'dim' },
  { key: 'heistL7z19', kit: 'lounge', floor: 'tiles', light: 'warm' },
  { key: 'heistL7z20', kit: 'stairs', floor: 'neon', light: 'dim' },
  { key: 'heistL7z21', kit: 'crates', floor: 'storage', light: 'dim' },
  { key: 'heistL7z22', kit: 'maze', floor: 'storage', light: 'dim' },
  { key: 'heistL7z23', kit: 'checkpoint', floor: 'steel', light: 'cool' },
  { key: 'heistL7z24', kit: 'crates', floor: 'concrete', light: 'dim' },
  { key: 'heistL7z25', kit: 'crates', floor: 'storage', light: 'dim' },
  { key: 'heistL7z26', kit: 'office', floor: 'bunker', light: 'dim' },
  { key: 'heistL7z27', kit: 'crates', floor: 'steel', light: 'cool' },
  { key: 'heistL7z28', kit: 'vaultRow', floor: 'storage', light: 'dim' },
  { key: 'heistL7z29', kit: 'corridor', floor: 'bunker', light: 'dim' },
  { key: 'heistL7z30', kit: 'stairs', floor: 'neon', light: 'dim' },
  { key: 'heistL7z31', kit: 'bunker', floor: 'bunker', light: 'dim' },
  { key: 'heistL7z32', kit: 'corridor', floor: 'bunker', light: 'dim' },
  { key: 'heistL7z33', kit: 'lab', floor: 'concrete', light: 'cool' },
  { key: 'heistL7z34', kit: 'crates', floor: 'storage', light: 'dim' },
  { key: 'heistL7z35', kit: 'control', floor: 'steel', light: 'blue' },
  { key: 'heistL7z36', kit: 'safeRoom', floor: 'vault', light: 'gold' },
  { key: 'heistL7z37', kit: 'bunker', floor: 'concrete', light: 'dim' },
  { key: 'heistL7z38', kit: 'corridor', floor: 'bunker', light: 'dim' },
  { key: 'heistL7z39', kit: 'control', floor: 'bunker', light: 'blue' },
  { key: 'heistL7z40', kit: 'stairs', floor: 'bunker', light: 'dim' },
  { key: 'heistL7z41', kit: 'collection', floor: 'neon', light: 'warm' },
  { key: 'heistL7z42', kit: 'collection', floor: 'wood', light: 'warm' },
  { key: 'heistL7z43', kit: 'collection', floor: 'carpetRed', light: 'warm' },
  { key: 'heistL7z44', kit: 'gallery', floor: 'mansionStone', light: 'dim' },
  { key: 'heistL7z45', kit: 'archive', floor: 'wood', light: 'dim' },
  { key: 'heistL7z46', kit: 'library', floor: 'wood', light: 'warm' },
  { key: 'heistL7z47', kit: 'gallery', floor: 'neon', light: 'dim' },
  { key: 'heistL7z48', kit: 'library', floor: 'wood', light: 'warm' },
  { key: 'heistL7z49', kit: 'safeRoom', floor: 'vault', light: 'gold' },
  { key: 'heistL7z50', kit: 'stairs', floor: 'neon', light: 'dim' },
  { key: 'heistL7z51', kit: 'lounge', floor: 'carpetRed', light: 'warm' },
  { key: 'heistL7z52', kit: 'casino', floor: 'neon', light: 'gold' },
  { key: 'heistL7z53', kit: 'lounge', floor: 'carpetRed', light: 'warm' },
  { key: 'heistL7z54', kit: 'bar', floor: 'neon', light: 'warm' },
  { key: 'heistL7z55', kit: 'casino', floor: 'carpetRed', light: 'warm' },
  { key: 'heistL7z56', kit: 'cashHall', floor: 'vault', light: 'gold' },
  { key: 'heistL7z57', kit: 'lounge', floor: 'carpetRed', light: 'dim' },
  { key: 'heistL7z58', kit: 'guardPost', floor: 'neon', light: 'blue' },
  { key: 'heistL7z59', kit: 'safeRoom', floor: 'vault', light: 'gold' },
  { key: 'heistL7z60', kit: 'stairs', floor: 'neon', light: 'dim' },
  { key: 'heistL7z61', kit: 'corridor', floor: 'bunker', light: 'dim' },
  { key: 'heistL7z62', kit: 'checkpoint', floor: 'steel', light: 'blue' },
  { key: 'heistL7z63', kit: 'laser', floor: 'steel', light: 'blue' },
  { key: 'heistL7z64', kit: 'barracks', floor: 'bunker', light: 'dim' },
  { key: 'heistL7z65', kit: 'control', floor: 'steel', light: 'blue' },
  { key: 'heistL7z66', kit: 'maze', floor: 'bunker', light: 'dim' },
  { key: 'heistL7z67', kit: 'control', floor: 'bunker', light: 'blue' },
  { key: 'heistL7z68', kit: 'corridor', floor: 'bunker', light: 'dim' },
  { key: 'heistL7z69', kit: 'vaultRow', floor: 'vault', light: 'gold' },
  { key: 'heistL7z70', kit: 'stairs', floor: 'bunker', light: 'dim' },
  { key: 'heistL7z71', kit: 'cashHall', floor: 'neon', light: 'gold' },
  { key: 'heistL7z72', kit: 'server', floor: 'neon', light: 'blue' },
  { key: 'heistL7z73', kit: 'bullion', floor: 'gold', light: 'gold' },
  { key: 'heistL7z74', kit: 'casino', floor: 'neon', light: 'warm' },
  { key: 'heistL7z75', kit: 'office', floor: 'neon', light: 'warm' },
  { key: 'heistL7z76', kit: 'jewels', floor: 'marbleWhite', light: 'gold' },
  { key: 'heistL7z77', kit: 'safeRoom', floor: 'vault', light: 'gold' },
  { key: 'heistL7z78', kit: 'vaultRow', floor: 'neon', light: 'gold' },
  { key: 'heistL7z79', kit: 'lounge', floor: 'carpetRed', light: 'warm' },
  { key: 'heistL7z80', kit: 'stairs', floor: 'neon', light: 'gold' },
  { key: 'heistL7z81', kit: 'atrium', floor: 'neon', light: 'gold' },
  { key: 'heistL7z82', kit: 'office', floor: 'carpetRed', light: 'warm' },
  { key: 'heistL7z83', kit: 'archive', floor: 'wood', light: 'dim' },
  { key: 'heistL7z84', kit: 'treasury', floor: 'gold', light: 'gold' },
  { key: 'heistL7z85', kit: 'bullion', floor: 'gold', light: 'gold' },
  { key: 'heistL7z86', kit: 'collection', floor: 'mansionStone', light: 'gold' },
  { key: 'heistL7z87', kit: 'safeRoom', floor: 'gold', light: 'gold' },
  { key: 'heistL7z88', kit: 'guardPost', floor: 'bunker', light: 'blue' },
  { key: 'heistL7z89', kit: 'maze', floor: 'neon', light: 'gold' },
  { key: 'heistL7z90', kit: 'finale', floor: 'gold', light: 'gold' },
]

const L8_ROOMS: GrandRoom[] = [
  { key: 'heistL8z1', kit: 'lobby', floor: 'obsidian', light: 'gold' },
  { key: 'heistL8z2', kit: 'atrium', floor: 'obsidian', light: 'warm' },
  { key: 'heistL8z3', kit: 'cashHall', floor: 'marbleWhite', light: 'warm' },
  { key: 'heistL8z4', kit: 'atrium', floor: 'marbleWhite', light: 'gold' },
  { key: 'heistL8z5', kit: 'reception', floor: 'obsidian', light: 'warm' },
  { key: 'heistL8z6', kit: 'guardPost', floor: 'obsidian', light: 'blue' },
  { key: 'heistL8z7', kit: 'laser', floor: 'obsidian', light: 'blue' },
  { key: 'heistL8z8', kit: 'reception', floor: 'carpetRed', light: 'warm' },
  { key: 'heistL8z9', kit: 'cashHall', floor: 'wood', light: 'warm' },
  { key: 'heistL8z10', kit: 'stairs', floor: 'obsidian', light: 'gold' },
  { key: 'heistL8z11', kit: 'gallery', floor: 'mansionStone', light: 'warm' },
  { key: 'heistL8z12', kit: 'collection', floor: 'mansionStone', light: 'gold' },
  { key: 'heistL8z13', kit: 'collection', floor: 'marbleWhite', light: 'warm' },
  { key: 'heistL8z14', kit: 'collection', floor: 'mansionStone', light: 'gold' },
  { key: 'heistL8z15', kit: 'gallery', floor: 'ballroom', light: 'warm' },
  { key: 'heistL8z16', kit: 'secret', floor: 'mansionStone', light: 'dim' },
  { key: 'heistL8z17', kit: 'archive', floor: 'wood', light: 'dim' },
  { key: 'heistL8z18', kit: 'collection', floor: 'obsidian', light: 'gold' },
  { key: 'heistL8z19', kit: 'safeRoom', floor: 'vault', light: 'gold' },
  { key: 'heistL8z20', kit: 'stairs', floor: 'obsidian', light: 'gold' },
  { key: 'heistL8z21', kit: 'gallery', floor: 'parquet', light: 'warm' },
  { key: 'heistL8z22', kit: 'gallery', floor: 'carpetRed', light: 'warm' },
  { key: 'heistL8z23', kit: 'gallery', floor: 'ballroom', light: 'gold' },
  { key: 'heistL8z24', kit: 'lab', floor: 'tiles', light: 'cool' },
  { key: 'heistL8z25', kit: 'gallery', floor: 'parquet', light: 'warm' },
  { key: 'heistL8z26', kit: 'gallery', floor: 'marbleWhite', light: 'warm' },
  { key: 'heistL8z27', kit: 'lab', floor: 'wood', light: 'warm' },
  { key: 'heistL8z28', kit: 'archive', floor: 'parquet', light: 'dim' },
  { key: 'heistL8z29', kit: 'safeRoom', floor: 'vault', light: 'gold' },
  { key: 'heistL8z30', kit: 'stairs', floor: 'obsidian', light: 'gold' },
  { key: 'heistL8z31', kit: 'laser', floor: 'obsidian', light: 'blue' },
  { key: 'heistL8z32', kit: 'laser', floor: 'steel', light: 'blue' },
  { key: 'heistL8z33', kit: 'maze', floor: 'glass', light: 'blue' },
  { key: 'heistL8z34', kit: 'laser', floor: 'obsidian', light: 'blue' },
  { key: 'heistL8z35', kit: 'control', floor: 'steel', light: 'blue' },
  { key: 'heistL8z36', kit: 'jewels', floor: 'vault', light: 'gold' },
  { key: 'heistL8z37', kit: 'laser', floor: 'steel', light: 'blue' },
  { key: 'heistL8z38', kit: 'laser', floor: 'obsidian', light: 'blue' },
  { key: 'heistL8z39', kit: 'control', floor: 'steel', light: 'blue' },
  { key: 'heistL8z40', kit: 'stairs', floor: 'obsidian', light: 'gold' },
  { key: 'heistL8z41', kit: 'jewels', floor: 'obsidian', light: 'gold' },
  { key: 'heistL8z42', kit: 'jewels', floor: 'marbleWhite', light: 'gold' },
  { key: 'heistL8z43', kit: 'jewels', floor: 'carpetRed', light: 'gold' },
  { key: 'heistL8z44', kit: 'jewels', floor: 'marbleWhite', light: 'gold' },
  { key: 'heistL8z45', kit: 'jewels', floor: 'ballroom', light: 'gold' },
  { key: 'heistL8z46', kit: 'jewels', floor: 'obsidian', light: 'gold' },
  { key: 'heistL8z47', kit: 'jewels', floor: 'vault', light: 'gold' },
  { key: 'heistL8z48', kit: 'lab', floor: 'steel', light: 'cool' },
  { key: 'heistL8z49', kit: 'safeRoom', floor: 'vault', light: 'gold' },
  { key: 'heistL8z50', kit: 'stairs', floor: 'obsidian', light: 'gold' },
  { key: 'heistL8z51', kit: 'atrium', floor: 'mansionStone', light: 'warm' },
  { key: 'heistL8z52', kit: 'collection', floor: 'mansionStone', light: 'warm' },
  { key: 'heistL8z53', kit: 'collection', floor: 'mansionStone', light: 'dim' },
  { key: 'heistL8z54', kit: 'gallery', floor: 'carpetRed', light: 'warm' },
  { key: 'heistL8z55', kit: 'treasury', floor: 'gold', light: 'gold' },
  { key: 'heistL8z56', kit: 'guardPost', floor: 'obsidian', light: 'blue' },
  { key: 'heistL8z57', kit: 'jewels', floor: 'obsidian', light: 'gold' },
  { key: 'heistL8z58', kit: 'maze', floor: 'vault', light: 'gold' },
  { key: 'heistL8z59', kit: 'safeRoom', floor: 'vault', light: 'gold' },
  { key: 'heistL8z60', kit: 'stairs', floor: 'obsidian', light: 'gold' },
  { key: 'heistL8z61', kit: 'collection', floor: 'obsidian', light: 'gold' },
  { key: 'heistL8z62', kit: 'office', floor: 'wood', light: 'warm' },
  { key: 'heistL8z63', kit: 'collection', floor: 'wood', light: 'warm' },
  { key: 'heistL8z64', kit: 'jewels', floor: 'marbleWhite', light: 'gold' },
  { key: 'heistL8z65', kit: 'collection', floor: 'marbleWhite', light: 'cool' },
  { key: 'heistL8z66', kit: 'collection', floor: 'marbleWhite', light: 'warm' },
  { key: 'heistL8z67', kit: 'secret', floor: 'obsidian', light: 'dim' },
  { key: 'heistL8z68', kit: 'office', floor: 'carpetRed', light: 'warm' },
  { key: 'heistL8z69', kit: 'safeRoom', floor: 'vault', light: 'gold' },
  { key: 'heistL8z70', kit: 'stairs', floor: 'obsidian', light: 'gold' },
  { key: 'heistL8z71', kit: 'atrium', floor: 'obsidian', light: 'gold' },
  { key: 'heistL8z72', kit: 'vaultRow', floor: 'obsidian', light: 'gold' },
  { key: 'heistL8z73', kit: 'bullion', floor: 'gold', light: 'gold' },
  { key: 'heistL8z74', kit: 'corridor', floor: 'obsidian', light: 'dim' },
  { key: 'heistL8z75', kit: 'maze', floor: 'obsidian', light: 'dim' },
  { key: 'heistL8z76', kit: 'vaultRow', floor: 'vault', light: 'gold' },
  { key: 'heistL8z77', kit: 'bullion', floor: 'gold', light: 'gold' },
  { key: 'heistL8z78', kit: 'laser', floor: 'obsidian', light: 'blue' },
  { key: 'heistL8z79', kit: 'safeRoom', floor: 'vault', light: 'gold' },
  { key: 'heistL8z80', kit: 'stairs', floor: 'obsidian', light: 'gold' },
  { key: 'heistL8z81', kit: 'barracks', floor: 'steel', light: 'cool' },
  { key: 'heistL8z82', kit: 'barracks', floor: 'obsidian', light: 'blue' },
  { key: 'heistL8z83', kit: 'control', floor: 'steel', light: 'blue' },
  { key: 'heistL8z84', kit: 'laser', floor: 'obsidian', light: 'blue' },
  { key: 'heistL8z85', kit: 'laser', floor: 'steel', light: 'blue' },
  { key: 'heistL8z86', kit: 'checkpoint', floor: 'steel', light: 'blue' },
  { key: 'heistL8z87', kit: 'control', floor: 'obsidian', light: 'blue' },
  { key: 'heistL8z88', kit: 'maze', floor: 'obsidian', light: 'dim' },
  { key: 'heistL8z89', kit: 'safeRoom', floor: 'vault', light: 'gold' },
  { key: 'heistL8z90', kit: 'stairs', floor: 'obsidian', light: 'gold' },
  { key: 'heistL8z91', kit: 'atrium', floor: 'obsidian', light: 'gold' },
  { key: 'heistL8z92', kit: 'jewels', floor: 'obsidian', light: 'gold' },
  { key: 'heistL8z93', kit: 'treasury', floor: 'gold', light: 'gold' },
  { key: 'heistL8z94', kit: 'collection', floor: 'gold', light: 'gold' },
  { key: 'heistL8z95', kit: 'jewels', floor: 'blackMarble', light: 'gold' },
  { key: 'heistL8z96', kit: 'treasury', floor: 'obsidian', light: 'gold' },
  { key: 'heistL8z97', kit: 'treasury', floor: 'gold', light: 'gold' },
  { key: 'heistL8z98', kit: 'guardPost', floor: 'obsidian', light: 'blue' },
  { key: 'heistL8z99', kit: 'maze', floor: 'obsidian', light: 'gold' },
  { key: 'heistL8z100', kit: 'finale', floor: 'gold', light: 'gold' },
]

export const GRAND_SPECS: Record<GrandLevelId, GrandSpec> = {
  level3: {
    id: 'level3',
    prefix: 'l3',
    floors: 5,
    rooms: L3_ROOMS,
    splitByFloor: [1000, 1000, 2000, 1000, 1000],
    lockAt: (f, k) => (k === 1 && f >= 1) || (k === 2 && f >= 3),
    archAt: (f, k) => (f >= 1 && (k === 1 || k === 2)) || (f >= 2 && k === 3),
    lockedSide: [16, 24, 33, 39, 42, 47],
    safes: safes([
      [8, 150, 'C50'], [16, 200, 'C50'], [19, 200, 'C100'], [24, 250, 'C100'], [28, 300, 'C100'], [33, 300, 'C100'],
      [35, 350, 'C100'], [39, 350, 'C100'], [42, 400, 'C100'], [45, 450, 'C100'], [47, 500, 'C100'], [48, 600, 'C100'],
    ]),
    loot: lootCurve({ c50: [1, 4.5], c100: [0.4, 4.6], finale: [4, 6] }, 50, 3),
    camsPerBand: (f, k) => (f === 0 ? (k === 1 || k === 3 ? 1 : 0) : f >= 3 && (k === 2 || k === 3) ? 2 : 1),
    camSpeed: (f) => 0.4 + f * 0.03,
    guardsPerBand: (f, k) => (f === 0 ? (k >= 2 ? 1 : 0) : f >= 3 && (k === 2 || k === 3) ? 2 : 1),
    background: 0x0a0e16,
    runner: { base: 0x14243a, gold: 0x2a3a52, edge: 0x8ec8f0 },
  },
  level4: {
    id: 'level4',
    prefix: 'l4',
    floors: 6,
    rooms: L4_ROOMS,
    splitByFloor: [1000, 1000, 2000, 1000, 2000, 2000],
    lockAt: (f, k) => (k === 1 && f >= 1) || (k === 2 && f >= 2) || (k === 0 && f >= 4),
    archAt: (f, k) => (f >= 1 && k === 2) || (f >= 2 && (k === 1 || k === 3)),
    lockedSide: [12, 17, 26, 37, 44, 46, 53, 56],
    safes: safes([
      [8, 200, 'C50'], [12, 200, 'C50'], [17, 250, 'C100'], [19, 300, 'C100'], [26, 300, 'C100'], [28, 350, 'C100'],
      [35, 400, 'C100'], [37, 400, 'C100'], [42, 450, 'C100'], [44, 450, 'C100'], [46, 500, 'C100'], [48, 550, 'C100'],
      [53, 600, 'C100'], [56, 700, 'C100'], [57, 800, 'C100'],
    ]),
    loot: lootCurve({ c50: [1.5, 5], c100: [0.8, 5.4], finale: [5, 8] }, 60, 4),
    camsPerBand: (f, k) => (f === 0 ? (k === 1 || k === 3 ? 1 : 0) : f >= 2 && (k === 2 || k === 3) ? 2 : 1),
    camSpeed: (f) => 0.42 + f * 0.03,
    guardsPerBand: (f, k) => (f === 0 ? (k >= 2 ? 1 : 0) : f >= 2 && (k === 2 || k === 3) ? 2 : f === 2 && k === 3 ? 2 : 1),
    background: 0x0c0909,
    runner: { base: 0x3a0c10, gold: 0x2a0a0c, edge: 0xc8323a },
  },
  level5: {
    id: 'level5',
    prefix: 'l5',
    floors: 7,
    rooms: L5_ROOMS,
    splitByFloor: [1000, 2000, 1000, 2000, 2000, 1000, 2000],
    lockAt: (f, k) => k === 1 || (k === 2 && f >= 1) || (k === 0 && f >= 3),
    archAt: (f, k) => (f >= 1 && k === 1) || (f >= 2 && (k === 2 || k === 3)),
    lockedSide: [19, 24, 26, 36, 43, 46, 47, 52, 54, 63],
    safes: safes([
      [8, 250, 'C50'], [15, 300, 'C100'], [19, 350, 'C100'], [24, 350, 'C100'], [26, 400, 'C100'], [28, 450, 'C100'],
      [36, 450, 'C100'], [38, 500, 'C100'], [43, 500, 'C100'], [46, 550, 'C100'], [47, 600, 'C100'], [48, 650, 'C100'],
      [52, 700, 'C100'], [54, 750, 'C100'], [58, 800, 'C100'], [63, 900, 'C100'], [65, 950, 'C100'], [68, 1000, 'C100'],
    ]),
    loot: lootCurve({ c50: [2, 5.5], c100: [1, 6.5], finale: [6, 10] }, 70, 5),
    camsPerBand: (f, k) => (f === 0 ? (k === 1 || k === 3 ? 1 : 0) : (k === 2 || k === 3) && f >= 1 ? 2 : 1),
    camSpeed: (f) => 0.44 + f * 0.03,
    guardsPerBand: (f, k) => (f === 0 ? (k >= 2 ? 1 : 0) : f >= 3 && (k === 2 || k === 3) ? 2 : f >= 5 && k === 1 ? 2 : 1),
    background: 0x0a0805,
    runner: { base: 0x120e08, gold: 0x3a2808, edge: 0xffd65a },
  },
  // LEVEL 6 SKYLINE TOWER — glass and steel, a lift in every floor hall (free: one floor, ⭐: express).
  level6: {
    id: 'level6',
    prefix: 'l6',
    floors: 8,
    rooms: L6_ROOMS,
    splitByFloor: [1000, 2000, 1000, 2000, 1000, 2000, 1000, 2000],
    lockAt: (f, k) => k === 1 || (k === 2 && f >= 1) || (k === 0 && f >= 3),
    archAt: (f, k) => (f >= 1 && k === 1) || (f >= 2 && (k === 2 || k === 3)),
    lockedSide: [8, 16, 26, 36, 46, 54, 66, 76],
    safes: safes([
      [7, 300, 'C50'], [16, 350, 'C100'], [19, 400, 'C100'], [26, 450, 'C100'], [28, 450, 'C100'], [35, 500, 'C100'],
      [38, 550, 'C100'], [46, 600, 'C100'], [48, 650, 'C100'], [54, 700, 'C100'], [58, 750, 'C100'], [66, 800, 'C100'],
      [68, 850, 'C100'], [74, 900, 'C100'], [76, 1000, 'C100'], [78, 1100, 'C100'],
    ]),
    loot: lootCurve({ c50: [2.2, 5.8], c100: [1.2, 7], finale: [7, 12] }, 80, 6),
    camsPerBand: (f, k) => (f === 0 ? (k === 1 || k === 3 ? 1 : 0) : (k === 2 || k === 3) ? 2 : 1),
    camSpeed: (f) => 0.44 + f * 0.025,
    guardsPerBand: (f, k) => (f === 0 ? (k >= 2 ? 1 : 0) : f >= 3 && (k === 2 || k === 3) ? 2 : f >= 6 && k === 1 ? 2 : 1),
    background: 0x0a0e14,
    runner: { base: 0x1c2836, gold: 0x2a3a4c, edge: 0xbfe8ff },
    features: {
      lifts: true,
      valuables: { zones: [4, 13, 18, 24, 33, 43, 47, 53, 57, 63, 67, 75], min: 150, max: 1200 },
    },
  },
  // LEVEL 7 UNDERGROUND CITY — neon black market: free down-escalators, ⭐ express escalators.
  level7: {
    id: 'level7',
    prefix: 'l7',
    floors: 9,
    rooms: L7_ROOMS,
    splitByFloor: [2000, 1000, 2000, 1000, 2000, 1000, 2000, 1000, 2000],
    lockAt: (f, k) => k === 1 || (k === 2 && f >= 1) || (k === 0 && f >= 2),
    archAt: (f, k) => f >= 1 && (k === 1 || k === 2 || (f >= 3 && k === 3)),
    lockedSide: [9, 18, 23, 36, 44, 53, 59, 68, 76, 84],
    safes: safes([
      [6, 300, 'C50'], [9, 350, 'C100'], [18, 400, 'C100'], [26, 450, 'C100'], [29, 450, 'C100'], [36, 500, 'C100'],
      [39, 550, 'C100'], [44, 600, 'C100'], [49, 650, 'C100'], [56, 700, 'C100'], [59, 750, 'C100'], [66, 800, 'C100'],
      [69, 850, 'C100'], [76, 900, 'C100'], [77, 950, 'C100'], [84, 1050, 'C100'], [87, 1150, 'C100'],
    ]),
    loot: lootCurve({ c50: [2.4, 6], c100: [1.4, 7.5], finale: [8, 13] }, 90, 7),
    camsPerBand: (f, k) => (f === 0 ? (k === 1 || k === 3 ? 1 : 0) : (k === 2 || k === 3) ? 2 : 1),
    camSpeed: (f) => 0.45 + f * 0.022,
    guardsPerBand: (f, k) => (f === 0 ? (k >= 2 ? 1 : 0) : f >= 3 && (k === 2 || k === 3) ? 2 : f >= 6 && k === 1 ? 2 : 1),
    background: 0x08070c,
    runner: { base: 0x2a0c28, gold: 0x3a2808, edge: 0xff3cb4 },
    features: {
      escalators: { free: true, express: true },
      valuables: { zones: [2, 12, 16, 25, 34, 42, 45, 55, 57, 64, 73, 78, 83, 86], min: 200, max: 1400 },
    },
  },
  // LEVEL 8 GRAND COLLECTION — obsidian museum-vault: laser corridors, laser vaults, security panels.
  level8: {
    id: 'level8',
    prefix: 'l8',
    floors: 10,
    rooms: L8_ROOMS,
    splitByFloor: [1000, 2000, 1000, 2000, 1000, 2000, 1000, 2000, 1000, 2000],
    lockAt: (f, k) => k === 1 || (k === 2 && f >= 1) || (k === 0 && f >= 2),
    archAt: (f, k) => (f >= 1 && k === 1) || (f >= 2 && (k === 2 || k === 3)),
    lockedSide: [8, 17, 26, 34, 44, 57, 64, 74, 84, 96],
    safes: safes([
      [7, 350, 'C50'], [19, 400, 'C100'], [29, 450, 'C100'], [34, 500, 'C100'], [39, 550, 'C100'], [44, 600, 'C100'],
      [49, 650, 'C100'], [54, 700, 'C100'], [59, 750, 'C100'], [64, 800, 'C100'], [69, 850, 'C100'], [74, 900, 'C100'],
      [79, 950, 'C100'], [84, 1000, 'C100'], [89, 1100, 'C100'], [94, 1200, 'C100'], [97, 1300, 'C100'], [98, 1400, 'C100'],
    ]),
    loot: lootCurve({ c50: [2.6, 6.2], c100: [1.6, 8], finale: [9, 15] }, 100, 8),
    camsPerBand: (f, k) => (f === 0 ? (k >= 1 ? 1 : 0) : (k === 2 || k === 3) ? 2 : 1),
    camSpeed: (f) => 0.46 + f * 0.02,
    guardsPerBand: (f, k) => (f === 0 ? (k >= 2 ? 1 : 0) : f >= 3 && (k === 2 || k === 3) ? 2 : f >= 7 && k === 1 ? 2 : 1),
    background: 0x060508,
    runner: { base: 0x14080c, gold: 0x3a2808, edge: 0xc9a227 },
    features: {
      lasers: { fromFloor: 1, doubleFromFloor: 5, vaultZones: [26, 36, 46, 66, 86] },
      valuables: { zones: [4, 16, 26, 33, 36, 43, 46, 53, 63, 66, 73, 83, 86, 93, 95], min: 250, max: 1600 },
    },
  },
}

export const GRAND_ZONES: Record<GrandLevelId, number> = { level3: 50, level4: 60, level5: 70, level6: 80, level7: 90, level8: 100 }

export function grandLevel(id: GrandLevelId): LevelDef {
  return buildGrandLevel(GRAND_SPECS[id])
}
